// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMetadata.proto

package com.github.mxsm.protocol.protobuf;

public interface ClientMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.protocol.protobuf.ClientMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *client ip
   * </pre>
   *
   * <code>uint32 serverIp = 1;</code>
   * @return The serverIp.
   */
  int getServerIp();

  /**
   * <pre>
   *client name
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *client name
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
