// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestHeader.proto

package com.github.mxsm.protocol.protobuf;

public interface MessageHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.protocol.protobuf.MessageHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *源IP
   * </pre>
   *
   * <code>int64 sourceAddress = 1;</code>
   * @return The sourceAddress.
   */
  long getSourceAddress();

  /**
   * <pre>
   *请求的远程IP地址
   * </pre>
   *
   * <code>int64 remoteAddress = 2;</code>
   * @return The remoteAddress.
   */
  long getRemoteAddress();
}
