// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemotingRequest.proto

package com.github.mxsm.protocol.protobuf;

/**
 * Protobuf type {@code com.github.mxsm.protocol.protobuf.RemotingCommand}
 */
public final class RemotingCommand extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.protocol.protobuf.RemotingCommand)
    RemotingCommandOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RemotingCommand.newBuilder() to construct.
  private RemotingCommand(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RemotingCommand() {
    commandType_ = 0;
    payload_ = com.google.protobuf.ByteString.EMPTY;
    resultMessage_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RemotingCommand();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RemotingCommand(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.github.mxsm.protocol.protobuf.RequestHeader.Builder subBuilder = null;
            if (requestHeaders_ != null) {
              subBuilder = requestHeaders_.toBuilder();
            }
            requestHeaders_ = input.readMessage(com.github.mxsm.protocol.protobuf.RequestHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(requestHeaders_);
              requestHeaders_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.github.mxsm.protocol.protobuf.ResponseHeader.Builder subBuilder = null;
            if (responseHeaders_ != null) {
              subBuilder = responseHeaders_.toBuilder();
            }
            responseHeaders_ = input.readMessage(com.github.mxsm.protocol.protobuf.ResponseHeader.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(responseHeaders_);
              responseHeaders_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            commandType_ = rawValue;
            break;
          }
          case 32: {

            code_ = input.readInt32();
            break;
          }
          case 40: {

            payloadCrc32_ = input.readInt32();
            break;
          }
          case 48: {

            oneway_ = input.readBool();
            break;
          }
          case 56: {

            commandId_ = input.readUInt64();
            break;
          }
          case 64: {

            createTimestamp_ = input.readUInt64();
            break;
          }
          case 74: {

            payload_ = input.readBytes();
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            resultMessage_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.mxsm.protocol.protobuf.RemotingRequest.internal_static_com_github_mxsm_protocol_protobuf_RemotingCommand_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.mxsm.protocol.protobuf.RemotingRequest.internal_static_com_github_mxsm_protocol_protobuf_RemotingCommand_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.mxsm.protocol.protobuf.RemotingCommand.class, com.github.mxsm.protocol.protobuf.RemotingCommand.Builder.class);
  }

  public static final int REQUESTHEADERS_FIELD_NUMBER = 1;
  private com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders_;
  /**
   * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
   * @return Whether the requestHeaders field is set.
   */
  @java.lang.Override
  public boolean hasRequestHeaders() {
    return requestHeaders_ != null;
  }
  /**
   * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
   * @return The requestHeaders.
   */
  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.RequestHeader getRequestHeaders() {
    return requestHeaders_ == null ? com.github.mxsm.protocol.protobuf.RequestHeader.getDefaultInstance() : requestHeaders_;
  }
  /**
   * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
   */
  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.RequestHeaderOrBuilder getRequestHeadersOrBuilder() {
    return getRequestHeaders();
  }

  public static final int RESPONSEHEADERS_FIELD_NUMBER = 2;
  private com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders_;
  /**
   * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
   * @return Whether the responseHeaders field is set.
   */
  @java.lang.Override
  public boolean hasResponseHeaders() {
    return responseHeaders_ != null;
  }
  /**
   * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
   * @return The responseHeaders.
   */
  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.ResponseHeader getResponseHeaders() {
    return responseHeaders_ == null ? com.github.mxsm.protocol.protobuf.ResponseHeader.getDefaultInstance() : responseHeaders_;
  }
  /**
   * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
   */
  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.ResponseHeaderOrBuilder getResponseHeadersOrBuilder() {
    return getResponseHeaders();
  }

  public static final int COMMANDTYPE_FIELD_NUMBER = 3;
  private int commandType_;
  /**
   * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 3;</code>
   * @return The enum numeric value on the wire for commandType.
   */
  @java.lang.Override public int getCommandTypeValue() {
    return commandType_;
  }
  /**
   * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 3;</code>
   * @return The commandType.
   */
  @java.lang.Override public com.github.mxsm.protocol.protobuf.constant.RemotingCommandType getCommandType() {
    @SuppressWarnings("deprecation")
    com.github.mxsm.protocol.protobuf.constant.RemotingCommandType result = com.github.mxsm.protocol.protobuf.constant.RemotingCommandType.valueOf(commandType_);
    return result == null ? com.github.mxsm.protocol.protobuf.constant.RemotingCommandType.UNRECOGNIZED : result;
  }

  public static final int CODE_FIELD_NUMBER = 4;
  private int code_;
  /**
   * <pre>
   **
   * when commandType is RemotingCommandType.REQUEST，code is request code ,
   * when commandType is RemotingCommandType.RESPONSE，code is response code
   * </pre>
   *
   * <code>int32 code = 4;</code>
   * @return The code.
   */
  @java.lang.Override
  public int getCode() {
    return code_;
  }

  public static final int PAYLOADCRC32_FIELD_NUMBER = 5;
  private int payloadCrc32_;
  /**
   * <code>int32 payloadCrc32 = 5;</code>
   * @return The payloadCrc32.
   */
  @java.lang.Override
  public int getPayloadCrc32() {
    return payloadCrc32_;
  }

  public static final int ONEWAY_FIELD_NUMBER = 6;
  private boolean oneway_;
  /**
   * <code>bool oneway = 6;</code>
   * @return The oneway.
   */
  @java.lang.Override
  public boolean getOneway() {
    return oneway_;
  }

  public static final int COMMANDID_FIELD_NUMBER = 7;
  private long commandId_;
  /**
   * <code>uint64 commandId = 7;</code>
   * @return The commandId.
   */
  @java.lang.Override
  public long getCommandId() {
    return commandId_;
  }

  public static final int CREATETIMESTAMP_FIELD_NUMBER = 8;
  private long createTimestamp_;
  /**
   * <code>uint64 createTimestamp = 8;</code>
   * @return The createTimestamp.
   */
  @java.lang.Override
  public long getCreateTimestamp() {
    return createTimestamp_;
  }

  public static final int PAYLOAD_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString payload_;
  /**
   * <code>bytes payload = 9;</code>
   * @return The payload.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPayload() {
    return payload_;
  }

  public static final int RESULTMESSAGE_FIELD_NUMBER = 10;
  private volatile java.lang.Object resultMessage_;
  /**
   * <pre>
   *A result message after a message is processed - typically an error message
   * </pre>
   *
   * <code>string resultMessage = 10;</code>
   * @return The resultMessage.
   */
  @java.lang.Override
  public java.lang.String getResultMessage() {
    java.lang.Object ref = resultMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      resultMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *A result message after a message is processed - typically an error message
   * </pre>
   *
   * <code>string resultMessage = 10;</code>
   * @return The bytes for resultMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getResultMessageBytes() {
    java.lang.Object ref = resultMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      resultMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (requestHeaders_ != null) {
      output.writeMessage(1, getRequestHeaders());
    }
    if (responseHeaders_ != null) {
      output.writeMessage(2, getResponseHeaders());
    }
    if (commandType_ != com.github.mxsm.protocol.protobuf.constant.RemotingCommandType.REQUEST.getNumber()) {
      output.writeEnum(3, commandType_);
    }
    if (code_ != 0) {
      output.writeInt32(4, code_);
    }
    if (payloadCrc32_ != 0) {
      output.writeInt32(5, payloadCrc32_);
    }
    if (oneway_ != false) {
      output.writeBool(6, oneway_);
    }
    if (commandId_ != 0L) {
      output.writeUInt64(7, commandId_);
    }
    if (createTimestamp_ != 0L) {
      output.writeUInt64(8, createTimestamp_);
    }
    if (!payload_.isEmpty()) {
      output.writeBytes(9, payload_);
    }
    if (!getResultMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, resultMessage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (requestHeaders_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getRequestHeaders());
    }
    if (responseHeaders_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResponseHeaders());
    }
    if (commandType_ != com.github.mxsm.protocol.protobuf.constant.RemotingCommandType.REQUEST.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, commandType_);
    }
    if (code_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, code_);
    }
    if (payloadCrc32_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, payloadCrc32_);
    }
    if (oneway_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, oneway_);
    }
    if (commandId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, commandId_);
    }
    if (createTimestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(8, createTimestamp_);
    }
    if (!payload_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, payload_);
    }
    if (!getResultMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, resultMessage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.mxsm.protocol.protobuf.RemotingCommand)) {
      return super.equals(obj);
    }
    com.github.mxsm.protocol.protobuf.RemotingCommand other = (com.github.mxsm.protocol.protobuf.RemotingCommand) obj;

    if (hasRequestHeaders() != other.hasRequestHeaders()) return false;
    if (hasRequestHeaders()) {
      if (!getRequestHeaders()
          .equals(other.getRequestHeaders())) return false;
    }
    if (hasResponseHeaders() != other.hasResponseHeaders()) return false;
    if (hasResponseHeaders()) {
      if (!getResponseHeaders()
          .equals(other.getResponseHeaders())) return false;
    }
    if (commandType_ != other.commandType_) return false;
    if (getCode()
        != other.getCode()) return false;
    if (getPayloadCrc32()
        != other.getPayloadCrc32()) return false;
    if (getOneway()
        != other.getOneway()) return false;
    if (getCommandId()
        != other.getCommandId()) return false;
    if (getCreateTimestamp()
        != other.getCreateTimestamp()) return false;
    if (!getPayload()
        .equals(other.getPayload())) return false;
    if (!getResultMessage()
        .equals(other.getResultMessage())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequestHeaders()) {
      hash = (37 * hash) + REQUESTHEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getRequestHeaders().hashCode();
    }
    if (hasResponseHeaders()) {
      hash = (37 * hash) + RESPONSEHEADERS_FIELD_NUMBER;
      hash = (53 * hash) + getResponseHeaders().hashCode();
    }
    hash = (37 * hash) + COMMANDTYPE_FIELD_NUMBER;
    hash = (53 * hash) + commandType_;
    hash = (37 * hash) + CODE_FIELD_NUMBER;
    hash = (53 * hash) + getCode();
    hash = (37 * hash) + PAYLOADCRC32_FIELD_NUMBER;
    hash = (53 * hash) + getPayloadCrc32();
    hash = (37 * hash) + ONEWAY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getOneway());
    hash = (37 * hash) + COMMANDID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCommandId());
    hash = (37 * hash) + CREATETIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCreateTimestamp());
    hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
    hash = (53 * hash) + getPayload().hashCode();
    hash = (37 * hash) + RESULTMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getResultMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.RemotingCommand parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.mxsm.protocol.protobuf.RemotingCommand prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.mxsm.protocol.protobuf.RemotingCommand}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.protocol.protobuf.RemotingCommand)
      com.github.mxsm.protocol.protobuf.RemotingCommandOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.protocol.protobuf.RemotingRequest.internal_static_com_github_mxsm_protocol_protobuf_RemotingCommand_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.protocol.protobuf.RemotingRequest.internal_static_com_github_mxsm_protocol_protobuf_RemotingCommand_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.protocol.protobuf.RemotingCommand.class, com.github.mxsm.protocol.protobuf.RemotingCommand.Builder.class);
    }

    // Construct using com.github.mxsm.protocol.protobuf.RemotingCommand.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (requestHeadersBuilder_ == null) {
        requestHeaders_ = null;
      } else {
        requestHeaders_ = null;
        requestHeadersBuilder_ = null;
      }
      if (responseHeadersBuilder_ == null) {
        responseHeaders_ = null;
      } else {
        responseHeaders_ = null;
        responseHeadersBuilder_ = null;
      }
      commandType_ = 0;

      code_ = 0;

      payloadCrc32_ = 0;

      oneway_ = false;

      commandId_ = 0L;

      createTimestamp_ = 0L;

      payload_ = com.google.protobuf.ByteString.EMPTY;

      resultMessage_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.mxsm.protocol.protobuf.RemotingRequest.internal_static_com_github_mxsm_protocol_protobuf_RemotingCommand_descriptor;
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.RemotingCommand getDefaultInstanceForType() {
      return com.github.mxsm.protocol.protobuf.RemotingCommand.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.RemotingCommand build() {
      com.github.mxsm.protocol.protobuf.RemotingCommand result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.RemotingCommand buildPartial() {
      com.github.mxsm.protocol.protobuf.RemotingCommand result = new com.github.mxsm.protocol.protobuf.RemotingCommand(this);
      if (requestHeadersBuilder_ == null) {
        result.requestHeaders_ = requestHeaders_;
      } else {
        result.requestHeaders_ = requestHeadersBuilder_.build();
      }
      if (responseHeadersBuilder_ == null) {
        result.responseHeaders_ = responseHeaders_;
      } else {
        result.responseHeaders_ = responseHeadersBuilder_.build();
      }
      result.commandType_ = commandType_;
      result.code_ = code_;
      result.payloadCrc32_ = payloadCrc32_;
      result.oneway_ = oneway_;
      result.commandId_ = commandId_;
      result.createTimestamp_ = createTimestamp_;
      result.payload_ = payload_;
      result.resultMessage_ = resultMessage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.mxsm.protocol.protobuf.RemotingCommand) {
        return mergeFrom((com.github.mxsm.protocol.protobuf.RemotingCommand)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.mxsm.protocol.protobuf.RemotingCommand other) {
      if (other == com.github.mxsm.protocol.protobuf.RemotingCommand.getDefaultInstance()) return this;
      if (other.hasRequestHeaders()) {
        mergeRequestHeaders(other.getRequestHeaders());
      }
      if (other.hasResponseHeaders()) {
        mergeResponseHeaders(other.getResponseHeaders());
      }
      if (other.commandType_ != 0) {
        setCommandTypeValue(other.getCommandTypeValue());
      }
      if (other.getCode() != 0) {
        setCode(other.getCode());
      }
      if (other.getPayloadCrc32() != 0) {
        setPayloadCrc32(other.getPayloadCrc32());
      }
      if (other.getOneway() != false) {
        setOneway(other.getOneway());
      }
      if (other.getCommandId() != 0L) {
        setCommandId(other.getCommandId());
      }
      if (other.getCreateTimestamp() != 0L) {
        setCreateTimestamp(other.getCreateTimestamp());
      }
      if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
        setPayload(other.getPayload());
      }
      if (!other.getResultMessage().isEmpty()) {
        resultMessage_ = other.resultMessage_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.mxsm.protocol.protobuf.RemotingCommand parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.mxsm.protocol.protobuf.RemotingCommand) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.mxsm.protocol.protobuf.RequestHeader, com.github.mxsm.protocol.protobuf.RequestHeader.Builder, com.github.mxsm.protocol.protobuf.RequestHeaderOrBuilder> requestHeadersBuilder_;
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     * @return Whether the requestHeaders field is set.
     */
    public boolean hasRequestHeaders() {
      return requestHeadersBuilder_ != null || requestHeaders_ != null;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     * @return The requestHeaders.
     */
    public com.github.mxsm.protocol.protobuf.RequestHeader getRequestHeaders() {
      if (requestHeadersBuilder_ == null) {
        return requestHeaders_ == null ? com.github.mxsm.protocol.protobuf.RequestHeader.getDefaultInstance() : requestHeaders_;
      } else {
        return requestHeadersBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     */
    public Builder setRequestHeaders(com.github.mxsm.protocol.protobuf.RequestHeader value) {
      if (requestHeadersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        requestHeaders_ = value;
        onChanged();
      } else {
        requestHeadersBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     */
    public Builder setRequestHeaders(
        com.github.mxsm.protocol.protobuf.RequestHeader.Builder builderForValue) {
      if (requestHeadersBuilder_ == null) {
        requestHeaders_ = builderForValue.build();
        onChanged();
      } else {
        requestHeadersBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     */
    public Builder mergeRequestHeaders(com.github.mxsm.protocol.protobuf.RequestHeader value) {
      if (requestHeadersBuilder_ == null) {
        if (requestHeaders_ != null) {
          requestHeaders_ =
            com.github.mxsm.protocol.protobuf.RequestHeader.newBuilder(requestHeaders_).mergeFrom(value).buildPartial();
        } else {
          requestHeaders_ = value;
        }
        onChanged();
      } else {
        requestHeadersBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     */
    public Builder clearRequestHeaders() {
      if (requestHeadersBuilder_ == null) {
        requestHeaders_ = null;
        onChanged();
      } else {
        requestHeaders_ = null;
        requestHeadersBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     */
    public com.github.mxsm.protocol.protobuf.RequestHeader.Builder getRequestHeadersBuilder() {
      
      onChanged();
      return getRequestHeadersFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     */
    public com.github.mxsm.protocol.protobuf.RequestHeaderOrBuilder getRequestHeadersOrBuilder() {
      if (requestHeadersBuilder_ != null) {
        return requestHeadersBuilder_.getMessageOrBuilder();
      } else {
        return requestHeaders_ == null ?
            com.github.mxsm.protocol.protobuf.RequestHeader.getDefaultInstance() : requestHeaders_;
      }
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RequestHeader requestHeaders = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.mxsm.protocol.protobuf.RequestHeader, com.github.mxsm.protocol.protobuf.RequestHeader.Builder, com.github.mxsm.protocol.protobuf.RequestHeaderOrBuilder> 
        getRequestHeadersFieldBuilder() {
      if (requestHeadersBuilder_ == null) {
        requestHeadersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.mxsm.protocol.protobuf.RequestHeader, com.github.mxsm.protocol.protobuf.RequestHeader.Builder, com.github.mxsm.protocol.protobuf.RequestHeaderOrBuilder>(
                getRequestHeaders(),
                getParentForChildren(),
                isClean());
        requestHeaders_ = null;
      }
      return requestHeadersBuilder_;
    }

    private com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.mxsm.protocol.protobuf.ResponseHeader, com.github.mxsm.protocol.protobuf.ResponseHeader.Builder, com.github.mxsm.protocol.protobuf.ResponseHeaderOrBuilder> responseHeadersBuilder_;
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     * @return Whether the responseHeaders field is set.
     */
    public boolean hasResponseHeaders() {
      return responseHeadersBuilder_ != null || responseHeaders_ != null;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     * @return The responseHeaders.
     */
    public com.github.mxsm.protocol.protobuf.ResponseHeader getResponseHeaders() {
      if (responseHeadersBuilder_ == null) {
        return responseHeaders_ == null ? com.github.mxsm.protocol.protobuf.ResponseHeader.getDefaultInstance() : responseHeaders_;
      } else {
        return responseHeadersBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     */
    public Builder setResponseHeaders(com.github.mxsm.protocol.protobuf.ResponseHeader value) {
      if (responseHeadersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        responseHeaders_ = value;
        onChanged();
      } else {
        responseHeadersBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     */
    public Builder setResponseHeaders(
        com.github.mxsm.protocol.protobuf.ResponseHeader.Builder builderForValue) {
      if (responseHeadersBuilder_ == null) {
        responseHeaders_ = builderForValue.build();
        onChanged();
      } else {
        responseHeadersBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     */
    public Builder mergeResponseHeaders(com.github.mxsm.protocol.protobuf.ResponseHeader value) {
      if (responseHeadersBuilder_ == null) {
        if (responseHeaders_ != null) {
          responseHeaders_ =
            com.github.mxsm.protocol.protobuf.ResponseHeader.newBuilder(responseHeaders_).mergeFrom(value).buildPartial();
        } else {
          responseHeaders_ = value;
        }
        onChanged();
      } else {
        responseHeadersBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     */
    public Builder clearResponseHeaders() {
      if (responseHeadersBuilder_ == null) {
        responseHeaders_ = null;
        onChanged();
      } else {
        responseHeaders_ = null;
        responseHeadersBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     */
    public com.github.mxsm.protocol.protobuf.ResponseHeader.Builder getResponseHeadersBuilder() {
      
      onChanged();
      return getResponseHeadersFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     */
    public com.github.mxsm.protocol.protobuf.ResponseHeaderOrBuilder getResponseHeadersOrBuilder() {
      if (responseHeadersBuilder_ != null) {
        return responseHeadersBuilder_.getMessageOrBuilder();
      } else {
        return responseHeaders_ == null ?
            com.github.mxsm.protocol.protobuf.ResponseHeader.getDefaultInstance() : responseHeaders_;
      }
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ResponseHeader responseHeaders = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.github.mxsm.protocol.protobuf.ResponseHeader, com.github.mxsm.protocol.protobuf.ResponseHeader.Builder, com.github.mxsm.protocol.protobuf.ResponseHeaderOrBuilder> 
        getResponseHeadersFieldBuilder() {
      if (responseHeadersBuilder_ == null) {
        responseHeadersBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.github.mxsm.protocol.protobuf.ResponseHeader, com.github.mxsm.protocol.protobuf.ResponseHeader.Builder, com.github.mxsm.protocol.protobuf.ResponseHeaderOrBuilder>(
                getResponseHeaders(),
                getParentForChildren(),
                isClean());
        responseHeaders_ = null;
      }
      return responseHeadersBuilder_;
    }

    private int commandType_ = 0;
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 3;</code>
     * @return The enum numeric value on the wire for commandType.
     */
    @java.lang.Override public int getCommandTypeValue() {
      return commandType_;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 3;</code>
     * @param value The enum numeric value on the wire for commandType to set.
     * @return This builder for chaining.
     */
    public Builder setCommandTypeValue(int value) {
      
      commandType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 3;</code>
     * @return The commandType.
     */
    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.constant.RemotingCommandType getCommandType() {
      @SuppressWarnings("deprecation")
      com.github.mxsm.protocol.protobuf.constant.RemotingCommandType result = com.github.mxsm.protocol.protobuf.constant.RemotingCommandType.valueOf(commandType_);
      return result == null ? com.github.mxsm.protocol.protobuf.constant.RemotingCommandType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 3;</code>
     * @param value The commandType to set.
     * @return This builder for chaining.
     */
    public Builder setCommandType(com.github.mxsm.protocol.protobuf.constant.RemotingCommandType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      commandType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandType() {
      
      commandType_ = 0;
      onChanged();
      return this;
    }

    private int code_ ;
    /**
     * <pre>
     **
     * when commandType is RemotingCommandType.REQUEST，code is request code ,
     * when commandType is RemotingCommandType.RESPONSE，code is response code
     * </pre>
     *
     * <code>int32 code = 4;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }
    /**
     * <pre>
     **
     * when commandType is RemotingCommandType.REQUEST，code is request code ,
     * when commandType is RemotingCommandType.RESPONSE，code is response code
     * </pre>
     *
     * <code>int32 code = 4;</code>
     * @param value The code to set.
     * @return This builder for chaining.
     */
    public Builder setCode(int value) {
      
      code_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * when commandType is RemotingCommandType.REQUEST，code is request code ,
     * when commandType is RemotingCommandType.RESPONSE，code is response code
     * </pre>
     *
     * <code>int32 code = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCode() {
      
      code_ = 0;
      onChanged();
      return this;
    }

    private int payloadCrc32_ ;
    /**
     * <code>int32 payloadCrc32 = 5;</code>
     * @return The payloadCrc32.
     */
    @java.lang.Override
    public int getPayloadCrc32() {
      return payloadCrc32_;
    }
    /**
     * <code>int32 payloadCrc32 = 5;</code>
     * @param value The payloadCrc32 to set.
     * @return This builder for chaining.
     */
    public Builder setPayloadCrc32(int value) {
      
      payloadCrc32_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 payloadCrc32 = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayloadCrc32() {
      
      payloadCrc32_ = 0;
      onChanged();
      return this;
    }

    private boolean oneway_ ;
    /**
     * <code>bool oneway = 6;</code>
     * @return The oneway.
     */
    @java.lang.Override
    public boolean getOneway() {
      return oneway_;
    }
    /**
     * <code>bool oneway = 6;</code>
     * @param value The oneway to set.
     * @return This builder for chaining.
     */
    public Builder setOneway(boolean value) {
      
      oneway_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool oneway = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearOneway() {
      
      oneway_ = false;
      onChanged();
      return this;
    }

    private long commandId_ ;
    /**
     * <code>uint64 commandId = 7;</code>
     * @return The commandId.
     */
    @java.lang.Override
    public long getCommandId() {
      return commandId_;
    }
    /**
     * <code>uint64 commandId = 7;</code>
     * @param value The commandId to set.
     * @return This builder for chaining.
     */
    public Builder setCommandId(long value) {
      
      commandId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 commandId = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearCommandId() {
      
      commandId_ = 0L;
      onChanged();
      return this;
    }

    private long createTimestamp_ ;
    /**
     * <code>uint64 createTimestamp = 8;</code>
     * @return The createTimestamp.
     */
    @java.lang.Override
    public long getCreateTimestamp() {
      return createTimestamp_;
    }
    /**
     * <code>uint64 createTimestamp = 8;</code>
     * @param value The createTimestamp to set.
     * @return This builder for chaining.
     */
    public Builder setCreateTimestamp(long value) {
      
      createTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint64 createTimestamp = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearCreateTimestamp() {
      
      createTimestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes payload = 9;</code>
     * @return The payload.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }
    /**
     * <code>bytes payload = 9;</code>
     * @param value The payload to set.
     * @return This builder for chaining.
     */
    public Builder setPayload(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      payload_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes payload = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayload() {
      
      payload_ = getDefaultInstance().getPayload();
      onChanged();
      return this;
    }

    private java.lang.Object resultMessage_ = "";
    /**
     * <pre>
     *A result message after a message is processed - typically an error message
     * </pre>
     *
     * <code>string resultMessage = 10;</code>
     * @return The resultMessage.
     */
    public java.lang.String getResultMessage() {
      java.lang.Object ref = resultMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resultMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *A result message after a message is processed - typically an error message
     * </pre>
     *
     * <code>string resultMessage = 10;</code>
     * @return The bytes for resultMessage.
     */
    public com.google.protobuf.ByteString
        getResultMessageBytes() {
      java.lang.Object ref = resultMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *A result message after a message is processed - typically an error message
     * </pre>
     *
     * <code>string resultMessage = 10;</code>
     * @param value The resultMessage to set.
     * @return This builder for chaining.
     */
    public Builder setResultMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      resultMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A result message after a message is processed - typically an error message
     * </pre>
     *
     * <code>string resultMessage = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearResultMessage() {
      
      resultMessage_ = getDefaultInstance().getResultMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *A result message after a message is processed - typically an error message
     * </pre>
     *
     * <code>string resultMessage = 10;</code>
     * @param value The bytes for resultMessage to set.
     * @return This builder for chaining.
     */
    public Builder setResultMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      resultMessage_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.protocol.protobuf.RemotingCommand)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.protocol.protobuf.RemotingCommand)
  private static final com.github.mxsm.protocol.protobuf.RemotingCommand DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.mxsm.protocol.protobuf.RemotingCommand();
  }

  public static com.github.mxsm.protocol.protobuf.RemotingCommand getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RemotingCommand>
      PARSER = new com.google.protobuf.AbstractParser<RemotingCommand>() {
    @java.lang.Override
    public RemotingCommand parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RemotingCommand(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RemotingCommand> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RemotingCommand> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.RemotingCommand getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

