// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemotingRequest.proto

package com.github.mxsm.protocol.protobuf;

public interface RemotingCommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.protocol.protobuf.RemotingCommand)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *命令类型
   * </pre>
   *
   * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 1;</code>
   * @return The enum numeric value on the wire for commandType.
   */
  int getCommandTypeValue();
  /**
   * <pre>
   *命令类型
   * </pre>
   *
   * <code>.com.github.mxsm.protocol.protobuf.RemotingCommandType commandType = 1;</code>
   * @return The commandType.
   */
  com.github.mxsm.protocol.protobuf.RemotingCommandType getCommandType();

  /**
   * <code>int32 requestCode = 2;</code>
   * @return The requestCode.
   */
  int getRequestCode();

  /**
   * <code>bool oneway = 3;</code>
   * @return The oneway.
   */
  boolean getOneway();

  /**
   * <code>uint64 commandId = 4;</code>
   * @return The commandId.
   */
  long getCommandId();
}
