// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RemotingCommandType.proto

package com.github.mxsm.protocol.protobuf;

public final class RemotingCommandTypeOuterClass {
  private RemotingCommandTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031RemotingCommandType.proto\022!com.github." +
      "mxsm.protocol.protobuf*2\n\023RemotingComman" +
      "dType\022\013\n\007CONNECT\020\000\022\016\n\nHEART_BEAT\020\001B%\n!co" +
      "m.github.mxsm.protocol.protobufP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
