// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestHeader.proto

package com.github.mxsm.protocol.protobuf;

public final class RequestHeaderOuterClass {
  private RequestHeaderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_protocol_protobuf_RequestHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_protocol_protobuf_RequestHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023RequestHeader.proto\022!com.github.mxsm.p" +
      "rotocol.protobuf\032\022TerminalType.proto\"\363\001\n" +
      "\rRequestHeader\022\020\n\010protocol\030\001 \001(\t\022\017\n\007vers" +
      "ion\030\002 \001(\t\022\025\n\rsourceAddress\030\003 \001(\r\022\025\n\rremo" +
      "teAddress\030\004 \001(\r\022\023\n\013contentType\030\006 \001(\t\022E\n\014" +
      "terminalType\030\007 \001(\0162/.com.github.mxsm.pro" +
      "tocol.protobuf.TerminalType\022\023\n\013deviceTok" +
      "en\030\010 \001(\t\022\016\n\006sender\030\t \001(\t\022\020\n\010receiver\030\n \001" +
      "(\tB%\n!com.github.mxsm.protocol.protobufP" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.mxsm.protocol.protobuf.constant.TerminalTypeOuterClass.getDescriptor(),
        });
    internal_static_com_github_mxsm_protocol_protobuf_RequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_mxsm_protocol_protobuf_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_protocol_protobuf_RequestHeader_descriptor,
        new java.lang.String[] { "Protocol", "Version", "SourceAddress", "RemoteAddress", "ContentType", "TerminalType", "DeviceToken", "Sender", "Receiver", });
    com.github.mxsm.protocol.protobuf.constant.TerminalTypeOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
