// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestHeaders.proto

package com.github.mxsm.protocol.protobuf;

/**
 * Protobuf type {@code com.github.mxsm.protocol.protobuf.RequestHeaders}
 */
public final class RequestHeaders extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.protocol.protobuf.RequestHeaders)
    RequestHeadersOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestHeaders.newBuilder() to construct.
  private RequestHeaders(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestHeaders() {
    protocol_ = "";
    version_ = "";
    contentType_ = "";
    terminalType_ = "";
    deviceToken_ = "";
    sender_ = "";
    receiver_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RequestHeaders();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestHeaders(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            protocol_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
          case 24: {

            sourceAddress_ = input.readInt64();
            break;
          }
          case 32: {

            remoteAddress_ = input.readInt64();
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            contentType_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            terminalType_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceToken_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            sender_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            receiver_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.mxsm.protocol.protobuf.RequestHeadersOuterClass.internal_static_com_github_mxsm_protocol_protobuf_RequestHeaders_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.mxsm.protocol.protobuf.RequestHeadersOuterClass.internal_static_com_github_mxsm_protocol_protobuf_RequestHeaders_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.mxsm.protocol.protobuf.RequestHeaders.class, com.github.mxsm.protocol.protobuf.RequestHeaders.Builder.class);
  }

  public static final int PROTOCOL_FIELD_NUMBER = 1;
  private volatile java.lang.Object protocol_;
  /**
   * <pre>
   *协议
   * </pre>
   *
   * <code>string protocol = 1;</code>
   * @return The protocol.
   */
  @java.lang.Override
  public java.lang.String getProtocol() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      protocol_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *协议
   * </pre>
   *
   * <code>string protocol = 1;</code>
   * @return The bytes for protocol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProtocolBytes() {
    java.lang.Object ref = protocol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      protocol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 2;
  private volatile java.lang.Object version_;
  /**
   * <pre>
   *协议版本号
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The version.
   */
  @java.lang.Override
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *协议版本号
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SOURCEADDRESS_FIELD_NUMBER = 3;
  private long sourceAddress_;
  /**
   * <pre>
   *源IP
   * </pre>
   *
   * <code>int64 sourceAddress = 3;</code>
   * @return The sourceAddress.
   */
  @java.lang.Override
  public long getSourceAddress() {
    return sourceAddress_;
  }

  public static final int REMOTEADDRESS_FIELD_NUMBER = 4;
  private long remoteAddress_;
  /**
   * <pre>
   *请求的远程IP地址
   * </pre>
   *
   * <code>int64 remoteAddress = 4;</code>
   * @return The remoteAddress.
   */
  @java.lang.Override
  public long getRemoteAddress() {
    return remoteAddress_;
  }

  public static final int CONTENTTYPE_FIELD_NUMBER = 6;
  private volatile java.lang.Object contentType_;
  /**
   * <pre>
   *内容类型
   * </pre>
   *
   * <code>string contentType = 6;</code>
   * @return The contentType.
   */
  @java.lang.Override
  public java.lang.String getContentType() {
    java.lang.Object ref = contentType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      contentType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *内容类型
   * </pre>
   *
   * <code>string contentType = 6;</code>
   * @return The bytes for contentType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentTypeBytes() {
    java.lang.Object ref = contentType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      contentType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TERMINALTYPE_FIELD_NUMBER = 7;
  private volatile java.lang.Object terminalType_;
  /**
   * <pre>
   *发送消息的终端
   * </pre>
   *
   * <code>string terminalType = 7;</code>
   * @return The terminalType.
   */
  @java.lang.Override
  public java.lang.String getTerminalType() {
    java.lang.Object ref = terminalType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      terminalType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *发送消息的终端
   * </pre>
   *
   * <code>string terminalType = 7;</code>
   * @return The bytes for terminalType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTerminalTypeBytes() {
    java.lang.Object ref = terminalType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      terminalType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICETOKEN_FIELD_NUMBER = 8;
  private volatile java.lang.Object deviceToken_;
  /**
   * <pre>
   *发送消息的终端设备号
   * </pre>
   *
   * <code>string deviceToken = 8;</code>
   * @return The deviceToken.
   */
  @java.lang.Override
  public java.lang.String getDeviceToken() {
    java.lang.Object ref = deviceToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceToken_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *发送消息的终端设备号
   * </pre>
   *
   * <code>string deviceToken = 8;</code>
   * @return The bytes for deviceToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceTokenBytes() {
    java.lang.Object ref = deviceToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SENDER_FIELD_NUMBER = 9;
  private volatile java.lang.Object sender_;
  /**
   * <pre>
   *消息发送者
   * </pre>
   *
   * <code>string sender = 9;</code>
   * @return The sender.
   */
  @java.lang.Override
  public java.lang.String getSender() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sender_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *消息发送者
   * </pre>
   *
   * <code>string sender = 9;</code>
   * @return The bytes for sender.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSenderBytes() {
    java.lang.Object ref = sender_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sender_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RECEIVER_FIELD_NUMBER = 10;
  private volatile java.lang.Object receiver_;
  /**
   * <pre>
   *消息接收者
   * </pre>
   *
   * <code>string receiver = 10;</code>
   * @return The receiver.
   */
  @java.lang.Override
  public java.lang.String getReceiver() {
    java.lang.Object ref = receiver_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      receiver_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *消息接收者
   * </pre>
   *
   * <code>string receiver = 10;</code>
   * @return The bytes for receiver.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReceiverBytes() {
    java.lang.Object ref = receiver_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      receiver_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getProtocolBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, protocol_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
    }
    if (sourceAddress_ != 0L) {
      output.writeInt64(3, sourceAddress_);
    }
    if (remoteAddress_ != 0L) {
      output.writeInt64(4, remoteAddress_);
    }
    if (!getContentTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, contentType_);
    }
    if (!getTerminalTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, terminalType_);
    }
    if (!getDeviceTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, deviceToken_);
    }
    if (!getSenderBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sender_);
    }
    if (!getReceiverBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, receiver_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getProtocolBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, protocol_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
    }
    if (sourceAddress_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, sourceAddress_);
    }
    if (remoteAddress_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, remoteAddress_);
    }
    if (!getContentTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, contentType_);
    }
    if (!getTerminalTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, terminalType_);
    }
    if (!getDeviceTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, deviceToken_);
    }
    if (!getSenderBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sender_);
    }
    if (!getReceiverBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, receiver_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.mxsm.protocol.protobuf.RequestHeaders)) {
      return super.equals(obj);
    }
    com.github.mxsm.protocol.protobuf.RequestHeaders other = (com.github.mxsm.protocol.protobuf.RequestHeaders) obj;

    if (!getProtocol()
        .equals(other.getProtocol())) return false;
    if (!getVersion()
        .equals(other.getVersion())) return false;
    if (getSourceAddress()
        != other.getSourceAddress()) return false;
    if (getRemoteAddress()
        != other.getRemoteAddress()) return false;
    if (!getContentType()
        .equals(other.getContentType())) return false;
    if (!getTerminalType()
        .equals(other.getTerminalType())) return false;
    if (!getDeviceToken()
        .equals(other.getDeviceToken())) return false;
    if (!getSender()
        .equals(other.getSender())) return false;
    if (!getReceiver()
        .equals(other.getReceiver())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
    hash = (53 * hash) + getProtocol().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (37 * hash) + SOURCEADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSourceAddress());
    hash = (37 * hash) + REMOTEADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRemoteAddress());
    hash = (37 * hash) + CONTENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getContentType().hashCode();
    hash = (37 * hash) + TERMINALTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getTerminalType().hashCode();
    hash = (37 * hash) + DEVICETOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceToken().hashCode();
    hash = (37 * hash) + SENDER_FIELD_NUMBER;
    hash = (53 * hash) + getSender().hashCode();
    hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
    hash = (53 * hash) + getReceiver().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.RequestHeaders parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.mxsm.protocol.protobuf.RequestHeaders prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.mxsm.protocol.protobuf.RequestHeaders}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.protocol.protobuf.RequestHeaders)
      com.github.mxsm.protocol.protobuf.RequestHeadersOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.protocol.protobuf.RequestHeadersOuterClass.internal_static_com_github_mxsm_protocol_protobuf_RequestHeaders_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.protocol.protobuf.RequestHeadersOuterClass.internal_static_com_github_mxsm_protocol_protobuf_RequestHeaders_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.protocol.protobuf.RequestHeaders.class, com.github.mxsm.protocol.protobuf.RequestHeaders.Builder.class);
    }

    // Construct using com.github.mxsm.protocol.protobuf.RequestHeaders.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      protocol_ = "";

      version_ = "";

      sourceAddress_ = 0L;

      remoteAddress_ = 0L;

      contentType_ = "";

      terminalType_ = "";

      deviceToken_ = "";

      sender_ = "";

      receiver_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.mxsm.protocol.protobuf.RequestHeadersOuterClass.internal_static_com_github_mxsm_protocol_protobuf_RequestHeaders_descriptor;
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.RequestHeaders getDefaultInstanceForType() {
      return com.github.mxsm.protocol.protobuf.RequestHeaders.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.RequestHeaders build() {
      com.github.mxsm.protocol.protobuf.RequestHeaders result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.RequestHeaders buildPartial() {
      com.github.mxsm.protocol.protobuf.RequestHeaders result = new com.github.mxsm.protocol.protobuf.RequestHeaders(this);
      result.protocol_ = protocol_;
      result.version_ = version_;
      result.sourceAddress_ = sourceAddress_;
      result.remoteAddress_ = remoteAddress_;
      result.contentType_ = contentType_;
      result.terminalType_ = terminalType_;
      result.deviceToken_ = deviceToken_;
      result.sender_ = sender_;
      result.receiver_ = receiver_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.mxsm.protocol.protobuf.RequestHeaders) {
        return mergeFrom((com.github.mxsm.protocol.protobuf.RequestHeaders)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.mxsm.protocol.protobuf.RequestHeaders other) {
      if (other == com.github.mxsm.protocol.protobuf.RequestHeaders.getDefaultInstance()) return this;
      if (!other.getProtocol().isEmpty()) {
        protocol_ = other.protocol_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      if (other.getSourceAddress() != 0L) {
        setSourceAddress(other.getSourceAddress());
      }
      if (other.getRemoteAddress() != 0L) {
        setRemoteAddress(other.getRemoteAddress());
      }
      if (!other.getContentType().isEmpty()) {
        contentType_ = other.contentType_;
        onChanged();
      }
      if (!other.getTerminalType().isEmpty()) {
        terminalType_ = other.terminalType_;
        onChanged();
      }
      if (!other.getDeviceToken().isEmpty()) {
        deviceToken_ = other.deviceToken_;
        onChanged();
      }
      if (!other.getSender().isEmpty()) {
        sender_ = other.sender_;
        onChanged();
      }
      if (!other.getReceiver().isEmpty()) {
        receiver_ = other.receiver_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.mxsm.protocol.protobuf.RequestHeaders parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.mxsm.protocol.protobuf.RequestHeaders) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object protocol_ = "";
    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 1;</code>
     * @return The protocol.
     */
    public java.lang.String getProtocol() {
      java.lang.Object ref = protocol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 1;</code>
     * @return The bytes for protocol.
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      java.lang.Object ref = protocol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 1;</code>
     * @param value The protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocol(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      protocol_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProtocol() {
      
      protocol_ = getDefaultInstance().getProtocol();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *协议
     * </pre>
     *
     * <code>string protocol = 1;</code>
     * @param value The bytes for protocol to set.
     * @return This builder for chaining.
     */
    public Builder setProtocolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      protocol_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     * @return The version.
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     * @return The bytes for version.
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *协议版本号
     * </pre>
     *
     * <code>string version = 2;</code>
     * @param value The bytes for version to set.
     * @return This builder for chaining.
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }

    private long sourceAddress_ ;
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>int64 sourceAddress = 3;</code>
     * @return The sourceAddress.
     */
    @java.lang.Override
    public long getSourceAddress() {
      return sourceAddress_;
    }
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>int64 sourceAddress = 3;</code>
     * @param value The sourceAddress to set.
     * @return This builder for chaining.
     */
    public Builder setSourceAddress(long value) {
      
      sourceAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>int64 sourceAddress = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceAddress() {
      
      sourceAddress_ = 0L;
      onChanged();
      return this;
    }

    private long remoteAddress_ ;
    /**
     * <pre>
     *请求的远程IP地址
     * </pre>
     *
     * <code>int64 remoteAddress = 4;</code>
     * @return The remoteAddress.
     */
    @java.lang.Override
    public long getRemoteAddress() {
      return remoteAddress_;
    }
    /**
     * <pre>
     *请求的远程IP地址
     * </pre>
     *
     * <code>int64 remoteAddress = 4;</code>
     * @param value The remoteAddress to set.
     * @return This builder for chaining.
     */
    public Builder setRemoteAddress(long value) {
      
      remoteAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求的远程IP地址
     * </pre>
     *
     * <code>int64 remoteAddress = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemoteAddress() {
      
      remoteAddress_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object contentType_ = "";
    /**
     * <pre>
     *内容类型
     * </pre>
     *
     * <code>string contentType = 6;</code>
     * @return The contentType.
     */
    public java.lang.String getContentType() {
      java.lang.Object ref = contentType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contentType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *内容类型
     * </pre>
     *
     * <code>string contentType = 6;</code>
     * @return The bytes for contentType.
     */
    public com.google.protobuf.ByteString
        getContentTypeBytes() {
      java.lang.Object ref = contentType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contentType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *内容类型
     * </pre>
     *
     * <code>string contentType = 6;</code>
     * @param value The contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      contentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *内容类型
     * </pre>
     *
     * <code>string contentType = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearContentType() {
      
      contentType_ = getDefaultInstance().getContentType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *内容类型
     * </pre>
     *
     * <code>string contentType = 6;</code>
     * @param value The bytes for contentType to set.
     * @return This builder for chaining.
     */
    public Builder setContentTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      contentType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object terminalType_ = "";
    /**
     * <pre>
     *发送消息的终端
     * </pre>
     *
     * <code>string terminalType = 7;</code>
     * @return The terminalType.
     */
    public java.lang.String getTerminalType() {
      java.lang.Object ref = terminalType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        terminalType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *发送消息的终端
     * </pre>
     *
     * <code>string terminalType = 7;</code>
     * @return The bytes for terminalType.
     */
    public com.google.protobuf.ByteString
        getTerminalTypeBytes() {
      java.lang.Object ref = terminalType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        terminalType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *发送消息的终端
     * </pre>
     *
     * <code>string terminalType = 7;</code>
     * @param value The terminalType to set.
     * @return This builder for chaining.
     */
    public Builder setTerminalType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      terminalType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送消息的终端
     * </pre>
     *
     * <code>string terminalType = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearTerminalType() {
      
      terminalType_ = getDefaultInstance().getTerminalType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送消息的终端
     * </pre>
     *
     * <code>string terminalType = 7;</code>
     * @param value The bytes for terminalType to set.
     * @return This builder for chaining.
     */
    public Builder setTerminalTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      terminalType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceToken_ = "";
    /**
     * <pre>
     *发送消息的终端设备号
     * </pre>
     *
     * <code>string deviceToken = 8;</code>
     * @return The deviceToken.
     */
    public java.lang.String getDeviceToken() {
      java.lang.Object ref = deviceToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *发送消息的终端设备号
     * </pre>
     *
     * <code>string deviceToken = 8;</code>
     * @return The bytes for deviceToken.
     */
    public com.google.protobuf.ByteString
        getDeviceTokenBytes() {
      java.lang.Object ref = deviceToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *发送消息的终端设备号
     * </pre>
     *
     * <code>string deviceToken = 8;</code>
     * @param value The deviceToken to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送消息的终端设备号
     * </pre>
     *
     * <code>string deviceToken = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceToken() {
      
      deviceToken_ = getDefaultInstance().getDeviceToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *发送消息的终端设备号
     * </pre>
     *
     * <code>string deviceToken = 8;</code>
     * @param value The bytes for deviceToken to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceToken_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sender_ = "";
    /**
     * <pre>
     *消息发送者
     * </pre>
     *
     * <code>string sender = 9;</code>
     * @return The sender.
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *消息发送者
     * </pre>
     *
     * <code>string sender = 9;</code>
     * @return The bytes for sender.
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *消息发送者
     * </pre>
     *
     * <code>string sender = 9;</code>
     * @param value The sender to set.
     * @return This builder for chaining.
     */
    public Builder setSender(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sender_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送者
     * </pre>
     *
     * <code>string sender = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearSender() {
      
      sender_ = getDefaultInstance().getSender();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息发送者
     * </pre>
     *
     * <code>string sender = 9;</code>
     * @param value The bytes for sender to set.
     * @return This builder for chaining.
     */
    public Builder setSenderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sender_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object receiver_ = "";
    /**
     * <pre>
     *消息接收者
     * </pre>
     *
     * <code>string receiver = 10;</code>
     * @return The receiver.
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *消息接收者
     * </pre>
     *
     * <code>string receiver = 10;</code>
     * @return The bytes for receiver.
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *消息接收者
     * </pre>
     *
     * <code>string receiver = 10;</code>
     * @param value The receiver to set.
     * @return This builder for chaining.
     */
    public Builder setReceiver(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      receiver_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息接收者
     * </pre>
     *
     * <code>string receiver = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearReceiver() {
      
      receiver_ = getDefaultInstance().getReceiver();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *消息接收者
     * </pre>
     *
     * <code>string receiver = 10;</code>
     * @param value The bytes for receiver to set.
     * @return This builder for chaining.
     */
    public Builder setReceiverBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      receiver_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.protocol.protobuf.RequestHeaders)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.protocol.protobuf.RequestHeaders)
  private static final com.github.mxsm.protocol.protobuf.RequestHeaders DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.mxsm.protocol.protobuf.RequestHeaders();
  }

  public static com.github.mxsm.protocol.protobuf.RequestHeaders getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RequestHeaders>
      PARSER = new com.google.protobuf.AbstractParser<RequestHeaders>() {
    @java.lang.Override
    public RequestHeaders parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestHeaders(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestHeaders> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestHeaders> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.RequestHeaders getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

