// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseHeader.proto

package com.github.mxsm.protocol.protobuf;

public interface ResponseHeadersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.protocol.protobuf.ResponseHeaders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *协议
   * </pre>
   *
   * <code>string protocol = 1;</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <pre>
   *协议
   * </pre>
   *
   * <code>string protocol = 1;</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <pre>
   *协议版本号
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   *协议版本号
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   *内容类型
   * </pre>
   *
   * <code>string contentType = 3;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <pre>
   *内容类型
   * </pre>
   *
   * <code>string contentType = 3;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <pre>
   *状态
   * </pre>
   *
   * <code>uint32 status = 4;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <pre>
   *消息发送者
   * </pre>
   *
   * <code>string sender = 5;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <pre>
   *消息发送者
   * </pre>
   *
   * <code>string sender = 5;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <pre>
   *消息接收者
   * </pre>
   *
   * <code>string receiver = 6;</code>
   * @return The receiver.
   */
  java.lang.String getReceiver();
  /**
   * <pre>
   *消息接收者
   * </pre>
   *
   * <code>string receiver = 6;</code>
   * @return The bytes for receiver.
   */
  com.google.protobuf.ByteString
      getReceiverBytes();
}
