// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResponseHeader.proto

package com.github.mxsm.protocol.protobuf;

public final class ResponseHeaderOuterClass {
  private ResponseHeaderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_protocol_protobuf_ResponseHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_protocol_protobuf_ResponseHeader_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ResponseHeader.proto\022!com.github.mxsm." +
      "protocol.protobuf\"z\n\016ResponseHeader\022\020\n\010p" +
      "rotocol\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\022\023\n\013conten" +
      "tType\030\003 \001(\t\022\016\n\006status\030\004 \001(\r\022\016\n\006sender\030\005 " +
      "\001(\t\022\020\n\010receiver\030\006 \001(\tB%\n!com.github.mxsm" +
      ".protocol.protobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_mxsm_protocol_protobuf_ResponseHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_mxsm_protocol_protobuf_ResponseHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_protocol_protobuf_ResponseHeader_descriptor,
        new java.lang.String[] { "Protocol", "Version", "ContentType", "Status", "Sender", "Receiver", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
