// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMetadata.proto

package com.github.mxsm.protocol.protobuf;

public final class ServerMetadataOuterClass {
  private ServerMetadataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ServerMetadata.proto\022!com.github.mxsm." +
      "protocol.protobuf\032\020ServerType.proto\032\024Cli" +
      "entMetadata.proto\"\346\001\n\016ServerMetadata\022\020\n\010" +
      "serverIp\030\001 \001(\r\022\022\n\nserverPort\030\002 \001(\r\022\014\n\004na" +
      "me\030\003 \001(\t\022A\n\nserverType\030\004 \001(\0162-.com.githu" +
      "b.mxsm.protocol.protobuf.ServerType\022\022\n\nc" +
      "lientNums\030\005 \001(\r\022I\n\016clientMetadata\030\006 \003(\0132" +
      "1.com.github.mxsm.protocol.protobuf.Clie" +
      "ntMetadataB%\n!com.github.mxsm.protocol.p" +
      "rotobufP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.mxsm.protocol.protobuf.constant.ServerTypeOuterClass.getDescriptor(),
          com.github.mxsm.protocol.protobuf.ClientMetadataOuterClass.getDescriptor(),
        });
    internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_descriptor,
        new java.lang.String[] { "ServerIp", "ServerPort", "Name", "ServerType", "ClientNums", "ClientMetadata", });
    com.github.mxsm.protocol.protobuf.constant.ServerTypeOuterClass.getDescriptor();
    com.github.mxsm.protocol.protobuf.ClientMetadataOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
