// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMetadata.proto

package com.github.mxsm.protocol.protobuf;

/**
 * Protobuf type {@code com.github.mxsm.protocol.protobuf.ServerMetadata}
 */
public final class ServerMetadata extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.protocol.protobuf.ServerMetadata)
    ServerMetadataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ServerMetadata.newBuilder() to construct.
  private ServerMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ServerMetadata() {
    name_ = "";
    serverType_ = 0;
    clientMetadata_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ServerMetadata();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ServerMetadata(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            serverIp_ = input.readUInt32();
            break;
          }
          case 16: {

            serverPort_ = input.readUInt32();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 32: {
            int rawValue = input.readEnum();

            serverType_ = rawValue;
            break;
          }
          case 40: {

            clientNums_ = input.readUInt32();
            break;
          }
          case 50: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              clientMetadata_ = new java.util.ArrayList<com.github.mxsm.protocol.protobuf.ClientMetadata>();
              mutable_bitField0_ |= 0x00000001;
            }
            clientMetadata_.add(
                input.readMessage(com.github.mxsm.protocol.protobuf.ClientMetadata.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        clientMetadata_ = java.util.Collections.unmodifiableList(clientMetadata_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.github.mxsm.protocol.protobuf.ServerMetadataOuterClass.internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.github.mxsm.protocol.protobuf.ServerMetadataOuterClass.internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.github.mxsm.protocol.protobuf.ServerMetadata.class, com.github.mxsm.protocol.protobuf.ServerMetadata.Builder.class);
  }

  public static final int SERVERIP_FIELD_NUMBER = 1;
  private int serverIp_;
  /**
   * <pre>
   *server ip
   * </pre>
   *
   * <code>uint32 serverIp = 1;</code>
   * @return The serverIp.
   */
  @java.lang.Override
  public int getServerIp() {
    return serverIp_;
  }

  public static final int SERVERPORT_FIELD_NUMBER = 2;
  private int serverPort_;
  /**
   * <pre>
   *server bind port
   * </pre>
   *
   * <code>uint32 serverPort = 2;</code>
   * @return The serverPort.
   */
  @java.lang.Override
  public int getServerPort() {
    return serverPort_;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *server name
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *server name
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVERTYPE_FIELD_NUMBER = 4;
  private int serverType_;
  /**
   * <code>.com.github.mxsm.protocol.protobuf.ServerType serverType = 4;</code>
   * @return The enum numeric value on the wire for serverType.
   */
  @java.lang.Override public int getServerTypeValue() {
    return serverType_;
  }
  /**
   * <code>.com.github.mxsm.protocol.protobuf.ServerType serverType = 4;</code>
   * @return The serverType.
   */
  @java.lang.Override public com.github.mxsm.protocol.protobuf.constant.ServerType getServerType() {
    @SuppressWarnings("deprecation")
    com.github.mxsm.protocol.protobuf.constant.ServerType result = com.github.mxsm.protocol.protobuf.constant.ServerType.valueOf(serverType_);
    return result == null ? com.github.mxsm.protocol.protobuf.constant.ServerType.UNRECOGNIZED : result;
  }

  public static final int CLIENTNUMS_FIELD_NUMBER = 5;
  private int clientNums_;
  /**
   * <pre>
   *connect server client nums
   * </pre>
   *
   * <code>uint32 clientNums = 5;</code>
   * @return The clientNums.
   */
  @java.lang.Override
  public int getClientNums() {
    return clientNums_;
  }

  public static final int CLIENTMETADATA_FIELD_NUMBER = 6;
  private java.util.List<com.github.mxsm.protocol.protobuf.ClientMetadata> clientMetadata_;
  /**
   * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
   */
  @java.lang.Override
  public java.util.List<com.github.mxsm.protocol.protobuf.ClientMetadata> getClientMetadataList() {
    return clientMetadata_;
  }
  /**
   * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.github.mxsm.protocol.protobuf.ClientMetadataOrBuilder> 
      getClientMetadataOrBuilderList() {
    return clientMetadata_;
  }
  /**
   * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
   */
  @java.lang.Override
  public int getClientMetadataCount() {
    return clientMetadata_.size();
  }
  /**
   * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
   */
  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.ClientMetadata getClientMetadata(int index) {
    return clientMetadata_.get(index);
  }
  /**
   * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
   */
  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.ClientMetadataOrBuilder getClientMetadataOrBuilder(
      int index) {
    return clientMetadata_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (serverIp_ != 0) {
      output.writeUInt32(1, serverIp_);
    }
    if (serverPort_ != 0) {
      output.writeUInt32(2, serverPort_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    if (serverType_ != com.github.mxsm.protocol.protobuf.constant.ServerType.MAGPIE_BRIDGE.getNumber()) {
      output.writeEnum(4, serverType_);
    }
    if (clientNums_ != 0) {
      output.writeUInt32(5, clientNums_);
    }
    for (int i = 0; i < clientMetadata_.size(); i++) {
      output.writeMessage(6, clientMetadata_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (serverIp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, serverIp_);
    }
    if (serverPort_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, serverPort_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    if (serverType_ != com.github.mxsm.protocol.protobuf.constant.ServerType.MAGPIE_BRIDGE.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, serverType_);
    }
    if (clientNums_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, clientNums_);
    }
    for (int i = 0; i < clientMetadata_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, clientMetadata_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.github.mxsm.protocol.protobuf.ServerMetadata)) {
      return super.equals(obj);
    }
    com.github.mxsm.protocol.protobuf.ServerMetadata other = (com.github.mxsm.protocol.protobuf.ServerMetadata) obj;

    if (getServerIp()
        != other.getServerIp()) return false;
    if (getServerPort()
        != other.getServerPort()) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (serverType_ != other.serverType_) return false;
    if (getClientNums()
        != other.getClientNums()) return false;
    if (!getClientMetadataList()
        .equals(other.getClientMetadataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVERIP_FIELD_NUMBER;
    hash = (53 * hash) + getServerIp();
    hash = (37 * hash) + SERVERPORT_FIELD_NUMBER;
    hash = (53 * hash) + getServerPort();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SERVERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + serverType_;
    hash = (37 * hash) + CLIENTNUMS_FIELD_NUMBER;
    hash = (53 * hash) + getClientNums();
    if (getClientMetadataCount() > 0) {
      hash = (37 * hash) + CLIENTMETADATA_FIELD_NUMBER;
      hash = (53 * hash) + getClientMetadataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.github.mxsm.protocol.protobuf.ServerMetadata parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.github.mxsm.protocol.protobuf.ServerMetadata prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.mxsm.protocol.protobuf.ServerMetadata}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.protocol.protobuf.ServerMetadata)
      com.github.mxsm.protocol.protobuf.ServerMetadataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.mxsm.protocol.protobuf.ServerMetadataOuterClass.internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.mxsm.protocol.protobuf.ServerMetadataOuterClass.internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.mxsm.protocol.protobuf.ServerMetadata.class, com.github.mxsm.protocol.protobuf.ServerMetadata.Builder.class);
    }

    // Construct using com.github.mxsm.protocol.protobuf.ServerMetadata.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getClientMetadataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      serverIp_ = 0;

      serverPort_ = 0;

      name_ = "";

      serverType_ = 0;

      clientNums_ = 0;

      if (clientMetadataBuilder_ == null) {
        clientMetadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        clientMetadataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.github.mxsm.protocol.protobuf.ServerMetadataOuterClass.internal_static_com_github_mxsm_protocol_protobuf_ServerMetadata_descriptor;
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.ServerMetadata getDefaultInstanceForType() {
      return com.github.mxsm.protocol.protobuf.ServerMetadata.getDefaultInstance();
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.ServerMetadata build() {
      com.github.mxsm.protocol.protobuf.ServerMetadata result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.ServerMetadata buildPartial() {
      com.github.mxsm.protocol.protobuf.ServerMetadata result = new com.github.mxsm.protocol.protobuf.ServerMetadata(this);
      int from_bitField0_ = bitField0_;
      result.serverIp_ = serverIp_;
      result.serverPort_ = serverPort_;
      result.name_ = name_;
      result.serverType_ = serverType_;
      result.clientNums_ = clientNums_;
      if (clientMetadataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          clientMetadata_ = java.util.Collections.unmodifiableList(clientMetadata_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.clientMetadata_ = clientMetadata_;
      } else {
        result.clientMetadata_ = clientMetadataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.github.mxsm.protocol.protobuf.ServerMetadata) {
        return mergeFrom((com.github.mxsm.protocol.protobuf.ServerMetadata)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.github.mxsm.protocol.protobuf.ServerMetadata other) {
      if (other == com.github.mxsm.protocol.protobuf.ServerMetadata.getDefaultInstance()) return this;
      if (other.getServerIp() != 0) {
        setServerIp(other.getServerIp());
      }
      if (other.getServerPort() != 0) {
        setServerPort(other.getServerPort());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.serverType_ != 0) {
        setServerTypeValue(other.getServerTypeValue());
      }
      if (other.getClientNums() != 0) {
        setClientNums(other.getClientNums());
      }
      if (clientMetadataBuilder_ == null) {
        if (!other.clientMetadata_.isEmpty()) {
          if (clientMetadata_.isEmpty()) {
            clientMetadata_ = other.clientMetadata_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureClientMetadataIsMutable();
            clientMetadata_.addAll(other.clientMetadata_);
          }
          onChanged();
        }
      } else {
        if (!other.clientMetadata_.isEmpty()) {
          if (clientMetadataBuilder_.isEmpty()) {
            clientMetadataBuilder_.dispose();
            clientMetadataBuilder_ = null;
            clientMetadata_ = other.clientMetadata_;
            bitField0_ = (bitField0_ & ~0x00000001);
            clientMetadataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getClientMetadataFieldBuilder() : null;
          } else {
            clientMetadataBuilder_.addAllMessages(other.clientMetadata_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.github.mxsm.protocol.protobuf.ServerMetadata parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.github.mxsm.protocol.protobuf.ServerMetadata) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int serverIp_ ;
    /**
     * <pre>
     *server ip
     * </pre>
     *
     * <code>uint32 serverIp = 1;</code>
     * @return The serverIp.
     */
    @java.lang.Override
    public int getServerIp() {
      return serverIp_;
    }
    /**
     * <pre>
     *server ip
     * </pre>
     *
     * <code>uint32 serverIp = 1;</code>
     * @param value The serverIp to set.
     * @return This builder for chaining.
     */
    public Builder setServerIp(int value) {
      
      serverIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *server ip
     * </pre>
     *
     * <code>uint32 serverIp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerIp() {
      
      serverIp_ = 0;
      onChanged();
      return this;
    }

    private int serverPort_ ;
    /**
     * <pre>
     *server bind port
     * </pre>
     *
     * <code>uint32 serverPort = 2;</code>
     * @return The serverPort.
     */
    @java.lang.Override
    public int getServerPort() {
      return serverPort_;
    }
    /**
     * <pre>
     *server bind port
     * </pre>
     *
     * <code>uint32 serverPort = 2;</code>
     * @param value The serverPort to set.
     * @return This builder for chaining.
     */
    public Builder setServerPort(int value) {
      
      serverPort_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *server bind port
     * </pre>
     *
     * <code>uint32 serverPort = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerPort() {
      
      serverPort_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *server name
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int serverType_ = 0;
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ServerType serverType = 4;</code>
     * @return The enum numeric value on the wire for serverType.
     */
    @java.lang.Override public int getServerTypeValue() {
      return serverType_;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ServerType serverType = 4;</code>
     * @param value The enum numeric value on the wire for serverType to set.
     * @return This builder for chaining.
     */
    public Builder setServerTypeValue(int value) {
      
      serverType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ServerType serverType = 4;</code>
     * @return The serverType.
     */
    @java.lang.Override
    public com.github.mxsm.protocol.protobuf.constant.ServerType getServerType() {
      @SuppressWarnings("deprecation")
      com.github.mxsm.protocol.protobuf.constant.ServerType result = com.github.mxsm.protocol.protobuf.constant.ServerType.valueOf(serverType_);
      return result == null ? com.github.mxsm.protocol.protobuf.constant.ServerType.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ServerType serverType = 4;</code>
     * @param value The serverType to set.
     * @return This builder for chaining.
     */
    public Builder setServerType(com.github.mxsm.protocol.protobuf.constant.ServerType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      serverType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.github.mxsm.protocol.protobuf.ServerType serverType = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearServerType() {
      
      serverType_ = 0;
      onChanged();
      return this;
    }

    private int clientNums_ ;
    /**
     * <pre>
     *connect server client nums
     * </pre>
     *
     * <code>uint32 clientNums = 5;</code>
     * @return The clientNums.
     */
    @java.lang.Override
    public int getClientNums() {
      return clientNums_;
    }
    /**
     * <pre>
     *connect server client nums
     * </pre>
     *
     * <code>uint32 clientNums = 5;</code>
     * @param value The clientNums to set.
     * @return This builder for chaining.
     */
    public Builder setClientNums(int value) {
      
      clientNums_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *connect server client nums
     * </pre>
     *
     * <code>uint32 clientNums = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearClientNums() {
      
      clientNums_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<com.github.mxsm.protocol.protobuf.ClientMetadata> clientMetadata_ =
      java.util.Collections.emptyList();
    private void ensureClientMetadataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        clientMetadata_ = new java.util.ArrayList<com.github.mxsm.protocol.protobuf.ClientMetadata>(clientMetadata_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.mxsm.protocol.protobuf.ClientMetadata, com.github.mxsm.protocol.protobuf.ClientMetadata.Builder, com.github.mxsm.protocol.protobuf.ClientMetadataOrBuilder> clientMetadataBuilder_;

    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public java.util.List<com.github.mxsm.protocol.protobuf.ClientMetadata> getClientMetadataList() {
      if (clientMetadataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(clientMetadata_);
      } else {
        return clientMetadataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public int getClientMetadataCount() {
      if (clientMetadataBuilder_ == null) {
        return clientMetadata_.size();
      } else {
        return clientMetadataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public com.github.mxsm.protocol.protobuf.ClientMetadata getClientMetadata(int index) {
      if (clientMetadataBuilder_ == null) {
        return clientMetadata_.get(index);
      } else {
        return clientMetadataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder setClientMetadata(
        int index, com.github.mxsm.protocol.protobuf.ClientMetadata value) {
      if (clientMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientMetadataIsMutable();
        clientMetadata_.set(index, value);
        onChanged();
      } else {
        clientMetadataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder setClientMetadata(
        int index, com.github.mxsm.protocol.protobuf.ClientMetadata.Builder builderForValue) {
      if (clientMetadataBuilder_ == null) {
        ensureClientMetadataIsMutable();
        clientMetadata_.set(index, builderForValue.build());
        onChanged();
      } else {
        clientMetadataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder addClientMetadata(com.github.mxsm.protocol.protobuf.ClientMetadata value) {
      if (clientMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientMetadataIsMutable();
        clientMetadata_.add(value);
        onChanged();
      } else {
        clientMetadataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder addClientMetadata(
        int index, com.github.mxsm.protocol.protobuf.ClientMetadata value) {
      if (clientMetadataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureClientMetadataIsMutable();
        clientMetadata_.add(index, value);
        onChanged();
      } else {
        clientMetadataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder addClientMetadata(
        com.github.mxsm.protocol.protobuf.ClientMetadata.Builder builderForValue) {
      if (clientMetadataBuilder_ == null) {
        ensureClientMetadataIsMutable();
        clientMetadata_.add(builderForValue.build());
        onChanged();
      } else {
        clientMetadataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder addClientMetadata(
        int index, com.github.mxsm.protocol.protobuf.ClientMetadata.Builder builderForValue) {
      if (clientMetadataBuilder_ == null) {
        ensureClientMetadataIsMutable();
        clientMetadata_.add(index, builderForValue.build());
        onChanged();
      } else {
        clientMetadataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder addAllClientMetadata(
        java.lang.Iterable<? extends com.github.mxsm.protocol.protobuf.ClientMetadata> values) {
      if (clientMetadataBuilder_ == null) {
        ensureClientMetadataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, clientMetadata_);
        onChanged();
      } else {
        clientMetadataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder clearClientMetadata() {
      if (clientMetadataBuilder_ == null) {
        clientMetadata_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        clientMetadataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public Builder removeClientMetadata(int index) {
      if (clientMetadataBuilder_ == null) {
        ensureClientMetadataIsMutable();
        clientMetadata_.remove(index);
        onChanged();
      } else {
        clientMetadataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public com.github.mxsm.protocol.protobuf.ClientMetadata.Builder getClientMetadataBuilder(
        int index) {
      return getClientMetadataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public com.github.mxsm.protocol.protobuf.ClientMetadataOrBuilder getClientMetadataOrBuilder(
        int index) {
      if (clientMetadataBuilder_ == null) {
        return clientMetadata_.get(index);  } else {
        return clientMetadataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public java.util.List<? extends com.github.mxsm.protocol.protobuf.ClientMetadataOrBuilder> 
         getClientMetadataOrBuilderList() {
      if (clientMetadataBuilder_ != null) {
        return clientMetadataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(clientMetadata_);
      }
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public com.github.mxsm.protocol.protobuf.ClientMetadata.Builder addClientMetadataBuilder() {
      return getClientMetadataFieldBuilder().addBuilder(
          com.github.mxsm.protocol.protobuf.ClientMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public com.github.mxsm.protocol.protobuf.ClientMetadata.Builder addClientMetadataBuilder(
        int index) {
      return getClientMetadataFieldBuilder().addBuilder(
          index, com.github.mxsm.protocol.protobuf.ClientMetadata.getDefaultInstance());
    }
    /**
     * <code>repeated .com.github.mxsm.protocol.protobuf.ClientMetadata clientMetadata = 6;</code>
     */
    public java.util.List<com.github.mxsm.protocol.protobuf.ClientMetadata.Builder> 
         getClientMetadataBuilderList() {
      return getClientMetadataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.github.mxsm.protocol.protobuf.ClientMetadata, com.github.mxsm.protocol.protobuf.ClientMetadata.Builder, com.github.mxsm.protocol.protobuf.ClientMetadataOrBuilder> 
        getClientMetadataFieldBuilder() {
      if (clientMetadataBuilder_ == null) {
        clientMetadataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.github.mxsm.protocol.protobuf.ClientMetadata, com.github.mxsm.protocol.protobuf.ClientMetadata.Builder, com.github.mxsm.protocol.protobuf.ClientMetadataOrBuilder>(
                clientMetadata_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        clientMetadata_ = null;
      }
      return clientMetadataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.protocol.protobuf.ServerMetadata)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.protocol.protobuf.ServerMetadata)
  private static final com.github.mxsm.protocol.protobuf.ServerMetadata DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.github.mxsm.protocol.protobuf.ServerMetadata();
  }

  public static com.github.mxsm.protocol.protobuf.ServerMetadata getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ServerMetadata>
      PARSER = new com.google.protobuf.AbstractParser<ServerMetadata>() {
    @java.lang.Override
    public ServerMetadata parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ServerMetadata(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ServerMetadata> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ServerMetadata> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.github.mxsm.protocol.protobuf.ServerMetadata getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

