// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TerminalType.proto

package com.github.mxsm.protocol.protobuf.constant;

/**
 * Protobuf enum {@code com.github.mxsm.protocol.protobuf.TerminalType}
 */
public enum TerminalType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>HARMONYOS = 0;</code>
   */
  HARMONYOS(0),
  /**
   * <code>ANDROID = 1;</code>
   */
  ANDROID(1),
  /**
   * <code>IOS = 2;</code>
   */
  IOS(2),
  /**
   * <code>WEB = 3;</code>
   */
  WEB(3),
  /**
   * <code>WINDOWS_DESKTOP = 4;</code>
   */
  WINDOWS_DESKTOP(4),
  /**
   * <code>OTHERS = 5;</code>
   */
  OTHERS(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>HARMONYOS = 0;</code>
   */
  public static final int HARMONYOS_VALUE = 0;
  /**
   * <code>ANDROID = 1;</code>
   */
  public static final int ANDROID_VALUE = 1;
  /**
   * <code>IOS = 2;</code>
   */
  public static final int IOS_VALUE = 2;
  /**
   * <code>WEB = 3;</code>
   */
  public static final int WEB_VALUE = 3;
  /**
   * <code>WINDOWS_DESKTOP = 4;</code>
   */
  public static final int WINDOWS_DESKTOP_VALUE = 4;
  /**
   * <code>OTHERS = 5;</code>
   */
  public static final int OTHERS_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TerminalType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TerminalType forNumber(int value) {
    switch (value) {
      case 0: return HARMONYOS;
      case 1: return ANDROID;
      case 2: return IOS;
      case 3: return WEB;
      case 4: return WINDOWS_DESKTOP;
      case 5: return OTHERS;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TerminalType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TerminalType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TerminalType>() {
          public TerminalType findValueByNumber(int number) {
            return TerminalType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.github.mxsm.protocol.protobuf.constant.TerminalTypeOuterClass.getDescriptor().getEnumTypes().get(0);
  }

  private static final TerminalType[] VALUES = values();

  public static TerminalType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TerminalType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:com.github.mxsm.protocol.protobuf.TerminalType)
}

