sudo: false # faster builds
os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge

language: java
jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

install: true

branches:
  only:
    - develop
    - master

script:
  - mvn clean
  - mvn package

after_success:
  - mvn test jacoco:report
  - mvn coveralls:report -DrepoToken=$REPO_TOKEN
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"
