sudo: false # faster builds
os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge

language: java
jdk:
  - openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

branches:
  only:
    - develop
    - master

before_script:
  - rm -rf $HOME/.m2/repository/org/glassfish/javax.el/3.0.1-b08

script:
  - mvn clean
  - mvn package

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"