sudo: false # faster builds
os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge

language: java
jdk:
  - oraclejdk11

cache:
  directories:
    - $HOME/.m2

install: true

branches:
  only:
    - develop
    - master

script:
  - mvn clean
  - mvn package

after_success:
  - bash <(curl -s https://codecov.io/bash)  -f build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml

after_failure:
  - echo "build failed!"