// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/protobuf.proto

package github.ant.mxsm.protocol.protobuf;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageProtobufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:github.ant.mxsm.protocol.protobuf.MessageProtobuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string protocol = 1;</code>
     */
    java.lang.String getProtocol();
    /**
     * <code>string protocol = 1;</code>
     */
    com.google.protobuf.ByteString
        getProtocolBytes();

    /**
     * <code>string version = 2;</code>
     */
    java.lang.String getVersion();
    /**
     * <code>string version = 2;</code>
     */
    com.google.protobuf.ByteString
        getVersionBytes();

    /**
     * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
     */
    boolean hasUser();
    /**
     * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
     */
    github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User getUser();
    /**
     * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
     */
    github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.UserOrBuilder getUserOrBuilder();

    /**
     * <code>string messageId = 4;</code>
     */
    java.lang.String getMessageId();
    /**
     * <code>string messageId = 4;</code>
     */
    com.google.protobuf.ByteString
        getMessageIdBytes();

    /**
     * <code>string messageType = 5;</code>
     */
    java.lang.String getMessageType();
    /**
     * <code>string messageType = 5;</code>
     */
    com.google.protobuf.ByteString
        getMessageTypeBytes();

    /**
     * <code>string ctrlMessageId = 6;</code>
     */
    java.lang.String getCtrlMessageId();
    /**
     * <code>string ctrlMessageId = 6;</code>
     */
    com.google.protobuf.ByteString
        getCtrlMessageIdBytes();

    /**
     * <code>int64 messageTime = 7;</code>
     */
    long getMessageTime();

    /**
     * <code>string mediaType = 8;</code>
     */
    java.lang.String getMediaType();
    /**
     * <code>string mediaType = 8;</code>
     */
    com.google.protobuf.ByteString
        getMediaTypeBytes();

    /**
     * <code>string fileType = 9;</code>
     */
    java.lang.String getFileType();
    /**
     * <code>string fileType = 9;</code>
     */
    com.google.protobuf.ByteString
        getFileTypeBytes();

    /**
     * <code>string sender = 10;</code>
     */
    java.lang.String getSender();
    /**
     * <code>string sender = 10;</code>
     */
    com.google.protobuf.ByteString
        getSenderBytes();

    /**
     * <code>string receiver = 11;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>string receiver = 11;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>bytes payload = 12;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code github.ant.mxsm.protocol.protobuf.MessageProtobuf}
   */
  public  static final class MessageProtobuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:github.ant.mxsm.protocol.protobuf.MessageProtobuf)
      MessageProtobufOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageProtobuf.newBuilder() to construct.
    private MessageProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageProtobuf() {
      protocol_ = "";
      version_ = "";
      messageId_ = "";
      messageType_ = "";
      ctrlMessageId_ = "";
      messageTime_ = 0L;
      mediaType_ = "";
      fileType_ = "";
      sender_ = "";
      receiver_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MessageProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              protocol_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              version_ = s;
              break;
            }
            case 26: {
              github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              messageId_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              messageType_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              ctrlMessageId_ = s;
              break;
            }
            case 56: {

              messageTime_ = input.readInt64();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              mediaType_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              fileType_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              sender_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 98: {

              payload_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.class, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.Builder.class);
    }

    public interface UserOrBuilder extends
        // @@protoc_insertion_point(interface_extends:github.ant.mxsm.protocol.protobuf.MessageProtobuf.User)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string userId = 1;</code>
       */
      java.lang.String getUserId();
      /**
       * <code>string userId = 1;</code>
       */
      com.google.protobuf.ByteString
          getUserIdBytes();

      /**
       * <code>string token = 2;</code>
       */
      java.lang.String getToken();
      /**
       * <code>string token = 2;</code>
       */
      com.google.protobuf.ByteString
          getTokenBytes();
    }
    /**
     * Protobuf type {@code github.ant.mxsm.protocol.protobuf.MessageProtobuf.User}
     */
    public  static final class User extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:github.ant.mxsm.protocol.protobuf.MessageProtobuf.User)
        UserOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use User.newBuilder() to construct.
      private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private User() {
        userId_ = "";
        token_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private User(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                userId_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                token_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.class, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.Builder.class);
      }

      public static final int USERID_FIELD_NUMBER = 1;
      private volatile java.lang.Object userId_;
      /**
       * <code>string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        }
      }
      /**
       * <code>string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TOKEN_FIELD_NUMBER = 2;
      private volatile java.lang.Object token_;
      /**
       * <code>string token = 2;</code>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          token_ = s;
          return s;
        }
      }
      /**
       * <code>string token = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getUserIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userId_);
        }
        if (!getTokenBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, token_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getUserIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userId_);
        }
        if (!getTokenBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, token_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User)) {
          return super.equals(obj);
        }
        github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User other = (github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User) obj;

        boolean result = true;
        result = result && getUserId()
            .equals(other.getUserId());
        result = result && getToken()
            .equals(other.getToken());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId().hashCode();
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code github.ant.mxsm.protocol.protobuf.MessageProtobuf.User}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:github.ant.mxsm.protocol.protobuf.MessageProtobuf.User)
          github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.UserOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.class, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.Builder.class);
        }

        // Construct using github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          userId_ = "";

          token_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_descriptor;
        }

        @java.lang.Override
        public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User getDefaultInstanceForType() {
          return github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.getDefaultInstance();
        }

        @java.lang.Override
        public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User build() {
          github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User buildPartial() {
          github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User result = new github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User(this);
          result.userId_ = userId_;
          result.token_ = token_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User) {
            return mergeFrom((github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User other) {
          if (other == github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.getDefaultInstance()) return this;
          if (!other.getUserId().isEmpty()) {
            userId_ = other.userId_;
            onChanged();
          }
          if (!other.getToken().isEmpty()) {
            token_ = other.token_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object userId_ = "";
        /**
         * <code>string userId = 1;</code>
         */
        public java.lang.String getUserId() {
          java.lang.Object ref = userId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            userId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string userId = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUserIdBytes() {
          java.lang.Object ref = userId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            userId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string userId = 1;</code>
         */
        public Builder setUserId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          userId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string userId = 1;</code>
         */
        public Builder clearUserId() {
          
          userId_ = getDefaultInstance().getUserId();
          onChanged();
          return this;
        }
        /**
         * <code>string userId = 1;</code>
         */
        public Builder setUserIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          userId_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object token_ = "";
        /**
         * <code>string token = 2;</code>
         */
        public java.lang.String getToken() {
          java.lang.Object ref = token_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            token_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string token = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTokenBytes() {
          java.lang.Object ref = token_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            token_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string token = 2;</code>
         */
        public Builder setToken(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          token_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string token = 2;</code>
         */
        public Builder clearToken() {
          
          token_ = getDefaultInstance().getToken();
          onChanged();
          return this;
        }
        /**
         * <code>string token = 2;</code>
         */
        public Builder setTokenBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          token_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:github.ant.mxsm.protocol.protobuf.MessageProtobuf.User)
      }

      // @@protoc_insertion_point(class_scope:github.ant.mxsm.protocol.protobuf.MessageProtobuf.User)
      private static final github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User();
      }

      public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<User>
          PARSER = new com.google.protobuf.AbstractParser<User>() {
        @java.lang.Override
        public User parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new User(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<User> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<User> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int PROTOCOL_FIELD_NUMBER = 1;
    private volatile java.lang.Object protocol_;
    /**
     * <code>string protocol = 1;</code>
     */
    public java.lang.String getProtocol() {
      java.lang.Object ref = protocol_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        protocol_ = s;
        return s;
      }
    }
    /**
     * <code>string protocol = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProtocolBytes() {
      java.lang.Object ref = protocol_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        protocol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 2;
    private volatile java.lang.Object version_;
    /**
     * <code>string version = 2;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      }
    }
    /**
     * <code>string version = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_FIELD_NUMBER = 3;
    private github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User user_;
    /**
     * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
     */
    public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User getUser() {
      return user_ == null ? github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.getDefaultInstance() : user_;
    }
    /**
     * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
     */
    public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.UserOrBuilder getUserOrBuilder() {
      return getUser();
    }

    public static final int MESSAGEID_FIELD_NUMBER = 4;
    private volatile java.lang.Object messageId_;
    /**
     * <code>string messageId = 4;</code>
     */
    public java.lang.String getMessageId() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageId_ = s;
        return s;
      }
    }
    /**
     * <code>string messageId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageIdBytes() {
      java.lang.Object ref = messageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETYPE_FIELD_NUMBER = 5;
    private volatile java.lang.Object messageType_;
    /**
     * <code>string messageType = 5;</code>
     */
    public java.lang.String getMessageType() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messageType_ = s;
        return s;
      }
    }
    /**
     * <code>string messageType = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMessageTypeBytes() {
      java.lang.Object ref = messageType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messageType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CTRLMESSAGEID_FIELD_NUMBER = 6;
    private volatile java.lang.Object ctrlMessageId_;
    /**
     * <code>string ctrlMessageId = 6;</code>
     */
    public java.lang.String getCtrlMessageId() {
      java.lang.Object ref = ctrlMessageId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ctrlMessageId_ = s;
        return s;
      }
    }
    /**
     * <code>string ctrlMessageId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getCtrlMessageIdBytes() {
      java.lang.Object ref = ctrlMessageId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ctrlMessageId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGETIME_FIELD_NUMBER = 7;
    private long messageTime_;
    /**
     * <code>int64 messageTime = 7;</code>
     */
    public long getMessageTime() {
      return messageTime_;
    }

    public static final int MEDIATYPE_FIELD_NUMBER = 8;
    private volatile java.lang.Object mediaType_;
    /**
     * <code>string mediaType = 8;</code>
     */
    public java.lang.String getMediaType() {
      java.lang.Object ref = mediaType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mediaType_ = s;
        return s;
      }
    }
    /**
     * <code>string mediaType = 8;</code>
     */
    public com.google.protobuf.ByteString
        getMediaTypeBytes() {
      java.lang.Object ref = mediaType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mediaType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FILETYPE_FIELD_NUMBER = 9;
    private volatile java.lang.Object fileType_;
    /**
     * <code>string fileType = 9;</code>
     */
    public java.lang.String getFileType() {
      java.lang.Object ref = fileType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fileType_ = s;
        return s;
      }
    }
    /**
     * <code>string fileType = 9;</code>
     */
    public com.google.protobuf.ByteString
        getFileTypeBytes() {
      java.lang.Object ref = fileType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fileType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENDER_FIELD_NUMBER = 10;
    private volatile java.lang.Object sender_;
    /**
     * <code>string sender = 10;</code>
     */
    public java.lang.String getSender() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sender_ = s;
        return s;
      }
    }
    /**
     * <code>string sender = 10;</code>
     */
    public com.google.protobuf.ByteString
        getSenderBytes() {
      java.lang.Object ref = sender_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sender_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECEIVER_FIELD_NUMBER = 11;
    private volatile java.lang.Object receiver_;
    /**
     * <code>string receiver = 11;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>string receiver = 11;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 12;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>bytes payload = 12;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getProtocolBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, protocol_);
      }
      if (!getVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, version_);
      }
      if (user_ != null) {
        output.writeMessage(3, getUser());
      }
      if (!getMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, messageId_);
      }
      if (!getMessageTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, messageType_);
      }
      if (!getCtrlMessageIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, ctrlMessageId_);
      }
      if (messageTime_ != 0L) {
        output.writeInt64(7, messageTime_);
      }
      if (!getMediaTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, mediaType_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, fileType_);
      }
      if (!getSenderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, receiver_);
      }
      if (!payload_.isEmpty()) {
        output.writeBytes(12, payload_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getProtocolBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, protocol_);
      }
      if (!getVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, version_);
      }
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUser());
      }
      if (!getMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, messageId_);
      }
      if (!getMessageTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, messageType_);
      }
      if (!getCtrlMessageIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, ctrlMessageId_);
      }
      if (messageTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, messageTime_);
      }
      if (!getMediaTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, mediaType_);
      }
      if (!getFileTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, fileType_);
      }
      if (!getSenderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, sender_);
      }
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, receiver_);
      }
      if (!payload_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, payload_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf)) {
        return super.equals(obj);
      }
      github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf other = (github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf) obj;

      boolean result = true;
      result = result && getProtocol()
          .equals(other.getProtocol());
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      result = result && getMessageId()
          .equals(other.getMessageId());
      result = result && getMessageType()
          .equals(other.getMessageType());
      result = result && getCtrlMessageId()
          .equals(other.getCtrlMessageId());
      result = result && (getMessageTime()
          == other.getMessageTime());
      result = result && getMediaType()
          .equals(other.getMediaType());
      result = result && getFileType()
          .equals(other.getFileType());
      result = result && getSender()
          .equals(other.getSender());
      result = result && getReceiver()
          .equals(other.getReceiver());
      result = result && getPayload()
          .equals(other.getPayload());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PROTOCOL_FIELD_NUMBER;
      hash = (53 * hash) + getProtocol().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (37 * hash) + MESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getMessageId().hashCode();
      hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMessageType().hashCode();
      hash = (37 * hash) + CTRLMESSAGEID_FIELD_NUMBER;
      hash = (53 * hash) + getCtrlMessageId().hashCode();
      hash = (37 * hash) + MESSAGETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMessageTime());
      hash = (37 * hash) + MEDIATYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMediaType().hashCode();
      hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
      hash = (53 * hash) + getFileType().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayload().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code github.ant.mxsm.protocol.protobuf.MessageProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:github.ant.mxsm.protocol.protobuf.MessageProtobuf)
        github.ant.mxsm.protocol.protobuf.Message.MessageProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.class, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.Builder.class);
      }

      // Construct using github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        protocol_ = "";

        version_ = "";

        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        messageId_ = "";

        messageType_ = "";

        ctrlMessageId_ = "";

        messageTime_ = 0L;

        mediaType_ = "";

        fileType_ = "";

        sender_ = "";

        receiver_ = "";

        payload_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return github.ant.mxsm.protocol.protobuf.Message.internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_descriptor;
      }

      @java.lang.Override
      public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf getDefaultInstanceForType() {
        return github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.getDefaultInstance();
      }

      @java.lang.Override
      public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf build() {
        github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf buildPartial() {
        github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf result = new github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf(this);
        result.protocol_ = protocol_;
        result.version_ = version_;
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        result.messageId_ = messageId_;
        result.messageType_ = messageType_;
        result.ctrlMessageId_ = ctrlMessageId_;
        result.messageTime_ = messageTime_;
        result.mediaType_ = mediaType_;
        result.fileType_ = fileType_;
        result.sender_ = sender_;
        result.receiver_ = receiver_;
        result.payload_ = payload_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf) {
          return mergeFrom((github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf other) {
        if (other == github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.getDefaultInstance()) return this;
        if (!other.getProtocol().isEmpty()) {
          protocol_ = other.protocol_;
          onChanged();
        }
        if (!other.getVersion().isEmpty()) {
          version_ = other.version_;
          onChanged();
        }
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        if (!other.getMessageId().isEmpty()) {
          messageId_ = other.messageId_;
          onChanged();
        }
        if (!other.getMessageType().isEmpty()) {
          messageType_ = other.messageType_;
          onChanged();
        }
        if (!other.getCtrlMessageId().isEmpty()) {
          ctrlMessageId_ = other.ctrlMessageId_;
          onChanged();
        }
        if (other.getMessageTime() != 0L) {
          setMessageTime(other.getMessageTime());
        }
        if (!other.getMediaType().isEmpty()) {
          mediaType_ = other.mediaType_;
          onChanged();
        }
        if (!other.getFileType().isEmpty()) {
          fileType_ = other.fileType_;
          onChanged();
        }
        if (!other.getSender().isEmpty()) {
          sender_ = other.sender_;
          onChanged();
        }
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.getPayload() != com.google.protobuf.ByteString.EMPTY) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object protocol_ = "";
      /**
       * <code>string protocol = 1;</code>
       */
      public java.lang.String getProtocol() {
        java.lang.Object ref = protocol_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          protocol_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string protocol = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProtocolBytes() {
        java.lang.Object ref = protocol_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          protocol_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string protocol = 1;</code>
       */
      public Builder setProtocol(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        protocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string protocol = 1;</code>
       */
      public Builder clearProtocol() {
        
        protocol_ = getDefaultInstance().getProtocol();
        onChanged();
        return this;
      }
      /**
       * <code>string protocol = 1;</code>
       */
      public Builder setProtocolBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        protocol_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object version_ = "";
      /**
       * <code>string version = 2;</code>
       */
      public java.lang.String getVersion() {
        java.lang.Object ref = version_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          version_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVersionBytes() {
        java.lang.Object ref = version_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          version_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder setVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string version = 2;</code>
       */
      public Builder setVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        version_ = value;
        onChanged();
        return this;
      }

      private github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.Builder, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.UserOrBuilder> userBuilder_;
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      public Builder setUser(github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      public Builder setUser(
          github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      public Builder mergeUser(github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.UserOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>.github.ant.mxsm.protocol.protobuf.MessageProtobuf.User user = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.Builder, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.User.Builder, github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf.UserOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }

      private java.lang.Object messageId_ = "";
      /**
       * <code>string messageId = 4;</code>
       */
      public java.lang.String getMessageId() {
        java.lang.Object ref = messageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getMessageIdBytes() {
        java.lang.Object ref = messageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageId = 4;</code>
       */
      public Builder setMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageId = 4;</code>
       */
      public Builder clearMessageId() {
        
        messageId_ = getDefaultInstance().getMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string messageId = 4;</code>
       */
      public Builder setMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object messageType_ = "";
      /**
       * <code>string messageType = 5;</code>
       */
      public java.lang.String getMessageType() {
        java.lang.Object ref = messageType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messageType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string messageType = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMessageTypeBytes() {
        java.lang.Object ref = messageType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messageType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string messageType = 5;</code>
       */
      public Builder setMessageType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string messageType = 5;</code>
       */
      public Builder clearMessageType() {
        
        messageType_ = getDefaultInstance().getMessageType();
        onChanged();
        return this;
      }
      /**
       * <code>string messageType = 5;</code>
       */
      public Builder setMessageTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messageType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ctrlMessageId_ = "";
      /**
       * <code>string ctrlMessageId = 6;</code>
       */
      public java.lang.String getCtrlMessageId() {
        java.lang.Object ref = ctrlMessageId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ctrlMessageId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ctrlMessageId = 6;</code>
       */
      public com.google.protobuf.ByteString
          getCtrlMessageIdBytes() {
        java.lang.Object ref = ctrlMessageId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ctrlMessageId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ctrlMessageId = 6;</code>
       */
      public Builder setCtrlMessageId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ctrlMessageId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ctrlMessageId = 6;</code>
       */
      public Builder clearCtrlMessageId() {
        
        ctrlMessageId_ = getDefaultInstance().getCtrlMessageId();
        onChanged();
        return this;
      }
      /**
       * <code>string ctrlMessageId = 6;</code>
       */
      public Builder setCtrlMessageIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ctrlMessageId_ = value;
        onChanged();
        return this;
      }

      private long messageTime_ ;
      /**
       * <code>int64 messageTime = 7;</code>
       */
      public long getMessageTime() {
        return messageTime_;
      }
      /**
       * <code>int64 messageTime = 7;</code>
       */
      public Builder setMessageTime(long value) {
        
        messageTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 messageTime = 7;</code>
       */
      public Builder clearMessageTime() {
        
        messageTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object mediaType_ = "";
      /**
       * <code>string mediaType = 8;</code>
       */
      public java.lang.String getMediaType() {
        java.lang.Object ref = mediaType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mediaType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mediaType = 8;</code>
       */
      public com.google.protobuf.ByteString
          getMediaTypeBytes() {
        java.lang.Object ref = mediaType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mediaType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mediaType = 8;</code>
       */
      public Builder setMediaType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mediaType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mediaType = 8;</code>
       */
      public Builder clearMediaType() {
        
        mediaType_ = getDefaultInstance().getMediaType();
        onChanged();
        return this;
      }
      /**
       * <code>string mediaType = 8;</code>
       */
      public Builder setMediaTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mediaType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object fileType_ = "";
      /**
       * <code>string fileType = 9;</code>
       */
      public java.lang.String getFileType() {
        java.lang.Object ref = fileType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fileType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string fileType = 9;</code>
       */
      public com.google.protobuf.ByteString
          getFileTypeBytes() {
        java.lang.Object ref = fileType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fileType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string fileType = 9;</code>
       */
      public Builder setFileType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        fileType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string fileType = 9;</code>
       */
      public Builder clearFileType() {
        
        fileType_ = getDefaultInstance().getFileType();
        onChanged();
        return this;
      }
      /**
       * <code>string fileType = 9;</code>
       */
      public Builder setFileTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        fileType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sender_ = "";
      /**
       * <code>string sender = 10;</code>
       */
      public java.lang.String getSender() {
        java.lang.Object ref = sender_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sender_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string sender = 10;</code>
       */
      public com.google.protobuf.ByteString
          getSenderBytes() {
        java.lang.Object ref = sender_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sender_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sender = 10;</code>
       */
      public Builder setSender(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 10;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }
      /**
       * <code>string sender = 10;</code>
       */
      public Builder setSenderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sender_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>string receiver = 11;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string receiver = 11;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string receiver = 11;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 11;</code>
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>string receiver = 11;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes payload = 12;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>bytes payload = 12;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes payload = 12;</code>
       */
      public Builder clearPayload() {
        
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:github.ant.mxsm.protocol.protobuf.MessageProtobuf)
    }

    // @@protoc_insertion_point(class_scope:github.ant.mxsm.protocol.protobuf.MessageProtobuf)
    private static final github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf();
    }

    public static github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageProtobuf>
        PARSER = new com.google.protobuf.AbstractParser<MessageProtobuf>() {
      @java.lang.Override
      public MessageProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageProtobuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MessageProtobuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageProtobuf> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public github.ant.mxsm.protocol.protobuf.Message.MessageProtobuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035main/resources/protobuf.proto\022!github." +
      "ant.mxsm.protocol.protobuf\"\316\002\n\017MessagePr" +
      "otobuf\022\020\n\010protocol\030\001 \001(\t\022\017\n\007version\030\002 \001(" +
      "\t\022E\n\004user\030\003 \001(\01327.github.ant.mxsm.protoc" +
      "ol.protobuf.MessageProtobuf.User\022\021\n\tmess" +
      "ageId\030\004 \001(\t\022\023\n\013messageType\030\005 \001(\t\022\025\n\rctrl" +
      "MessageId\030\006 \001(\t\022\023\n\013messageTime\030\007 \001(\003\022\021\n\t" +
      "mediaType\030\010 \001(\t\022\020\n\010fileType\030\t \001(\t\022\016\n\006sen" +
      "der\030\n \001(\t\022\020\n\010receiver\030\013 \001(\t\022\017\n\007payload\030\014" +
      " \001(\014\032%\n\004User\022\016\n\006userId\030\001 \001(\t\022\r\n\005token\030\002 " +
      "\001(\tB,\n!github.ant.mxsm.protocol.protobuf" +
      "B\007Messageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_descriptor,
        new java.lang.String[] { "Protocol", "Version", "User", "MessageId", "MessageType", "CtrlMessageId", "MessageTime", "MediaType", "FileType", "Sender", "Receiver", "Payload", });
    internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_descriptor =
      internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_descriptor.getNestedTypes().get(0);
    internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_github_ant_mxsm_protocol_protobuf_MessageProtobuf_User_descriptor,
        new java.lang.String[] { "UserId", "Token", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
