logging:
  level:
    root: INFO

spring:
  mxsm:
    zkclient:
      servers: 127.0.0.1:2181
      seesionTimeout: 2000
      connectionTimeout: 2000
      operationRetryTimeout: 1000
      connectionTimeoutTimeUnit: SECONDS
      zookeeperSerializerClass: github.mxsm.zkclient.serializer.FasterJsonSerializer

etcd:
  endpoints: 127.0.0.1