// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MagpieBridge.proto

package com.github.mxsm.protocol.protobuf.magpiebridge;

public final class MagpieBridgeOuterClass {
  private MagpieBridgeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_github_mxsm_protocol_protobuf_magpiebridge_MagpieBridge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_github_mxsm_protocol_protobuf_magpiebridge_MagpieBridge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022MagpieBridge.proto\022.com.github.mxsm.pr" +
      "otocol.protobuf.magpiebridge\"\202\001\n\014MagpieB" +
      "ridge\022\030\n\020magpieBridgeName\030\001 \001(\t\022\033\n\023magpi" +
      "eBridgeAddress\030\002 \001(\t\022\026\n\016magpieBridgeId\030\003" +
      " \001(\r\022#\n\033magpieBridgeCreateTimestamp\030\004 \001(" +
      "\004B2\n.com.github.mxsm.protocol.protobuf.m" +
      "agpiebridgeP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_github_mxsm_protocol_protobuf_magpiebridge_MagpieBridge_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_github_mxsm_protocol_protobuf_magpiebridge_MagpieBridge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_github_mxsm_protocol_protobuf_magpiebridge_MagpieBridge_descriptor,
        new java.lang.String[] { "MagpieBridgeName", "MagpieBridgeAddress", "MagpieBridgeId", "MagpieBridgeCreateTimestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
