// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerType.proto

package com.github.mxsm.protocol.protobuf.constant;

public final class ServerTypeOuterClass {
  private ServerTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ServerType.proto\022!com.github.mxsm.prot" +
      "ocol.protobuf*9\n\nServerType\022\021\n\rMAGPIE_BR" +
      "IDGE\020\000\022\014\n\010REGISTER\020\001\022\n\n\006GALAXY\020\002B.\n*com." +
      "github.mxsm.protocol.protobuf.constantP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
