// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TerminalType.proto

package com.github.mxsm.protocol.protobuf.constant;

public final class TerminalTypeOuterClass {
  private TerminalTypeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022TerminalType.proto\022!com.github.mxsm.pr" +
      "otocol.protobuf*]\n\014TerminalType\022\r\n\tHARMO" +
      "NYOS\020\000\022\013\n\007ANDROID\020\001\022\007\n\003IOS\020\002\022\007\n\003WEB\020\003\022\023\n" +
      "\017WINDOWS_DESKTOP\020\004\022\n\n\006OTHERS\020\005B.\n*com.gi" +
      "thub.mxsm.protocol.protobuf.constantP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
