// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestHeaders.proto

package com.github.mxsm.protocol.protobuf;

/**
 * Protobuf type {@code com.github.mxsm.protocol.protobuf.MessageHeader}
 */
public final class MessageHeader extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.github.mxsm.protocol.protobuf.MessageHeader)
    MessageHeaderOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MessageHeader.newBuilder() to construct.
  private MessageHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MessageHeader() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new MessageHeader();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MessageHeader(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            sourceAddress_ = input.readInt64();
            break;
          }
          case 16: {

            remoteAddress_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MessageHeaderOuterClass.internal_static_com_github_mxsm_protocol_protobuf_MessageHeader_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MessageHeaderOuterClass.internal_static_com_github_mxsm_protocol_protobuf_MessageHeader_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            MessageHeader.class, Builder.class);
  }

  public static final int SOURCEADDRESS_FIELD_NUMBER = 1;
  private long sourceAddress_;
  /**
   * <pre>
   *源IP
   * </pre>
   *
   * <code>int64 sourceAddress = 1;</code>
   * @return The sourceAddress.
   */
  @Override
  public long getSourceAddress() {
    return sourceAddress_;
  }

  public static final int REMOTEADDRESS_FIELD_NUMBER = 2;
  private long remoteAddress_;
  /**
   * <pre>
   *请求的远程IP地址
   * </pre>
   *
   * <code>int64 remoteAddress = 2;</code>
   * @return The remoteAddress.
   */
  @Override
  public long getRemoteAddress() {
    return remoteAddress_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sourceAddress_ != 0L) {
      output.writeInt64(1, sourceAddress_);
    }
    if (remoteAddress_ != 0L) {
      output.writeInt64(2, remoteAddress_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sourceAddress_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, sourceAddress_);
    }
    if (remoteAddress_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, remoteAddress_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof MessageHeader)) {
      return super.equals(obj);
    }
    MessageHeader other = (MessageHeader) obj;

    if (getSourceAddress()
        != other.getSourceAddress()) return false;
    if (getRemoteAddress()
        != other.getRemoteAddress()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SOURCEADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getSourceAddress());
    hash = (37 * hash) + REMOTEADDRESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getRemoteAddress());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static MessageHeader parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageHeader parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageHeader parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageHeader parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageHeader parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static MessageHeader parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static MessageHeader parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MessageHeader parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static MessageHeader parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static MessageHeader parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static MessageHeader parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static MessageHeader parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(MessageHeader prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.github.mxsm.protocol.protobuf.MessageHeader}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.github.mxsm.protocol.protobuf.MessageHeader)
      MessageHeaderOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageHeaderOuterClass.internal_static_com_github_mxsm_protocol_protobuf_MessageHeader_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageHeaderOuterClass.internal_static_com_github_mxsm_protocol_protobuf_MessageHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MessageHeader.class, Builder.class);
    }

    // Construct using com.github.mxsm.protocol.protobuf.MessageHeader.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      sourceAddress_ = 0L;

      remoteAddress_ = 0L;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MessageHeaderOuterClass.internal_static_com_github_mxsm_protocol_protobuf_MessageHeader_descriptor;
    }

    @Override
    public MessageHeader getDefaultInstanceForType() {
      return MessageHeader.getDefaultInstance();
    }

    @Override
    public MessageHeader build() {
      MessageHeader result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public MessageHeader buildPartial() {
      MessageHeader result = new MessageHeader(this);
      result.sourceAddress_ = sourceAddress_;
      result.remoteAddress_ = remoteAddress_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof MessageHeader) {
        return mergeFrom((MessageHeader)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(MessageHeader other) {
      if (other == MessageHeader.getDefaultInstance()) return this;
      if (other.getSourceAddress() != 0L) {
        setSourceAddress(other.getSourceAddress());
      }
      if (other.getRemoteAddress() != 0L) {
        setRemoteAddress(other.getRemoteAddress());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      MessageHeader parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (MessageHeader) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long sourceAddress_ ;
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>int64 sourceAddress = 1;</code>
     * @return The sourceAddress.
     */
    @Override
    public long getSourceAddress() {
      return sourceAddress_;
    }
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>int64 sourceAddress = 1;</code>
     * @param value The sourceAddress to set.
     * @return This builder for chaining.
     */
    public Builder setSourceAddress(long value) {
      
      sourceAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *源IP
     * </pre>
     *
     * <code>int64 sourceAddress = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceAddress() {
      
      sourceAddress_ = 0L;
      onChanged();
      return this;
    }

    private long remoteAddress_ ;
    /**
     * <pre>
     *请求的远程IP地址
     * </pre>
     *
     * <code>int64 remoteAddress = 2;</code>
     * @return The remoteAddress.
     */
    @Override
    public long getRemoteAddress() {
      return remoteAddress_;
    }
    /**
     * <pre>
     *请求的远程IP地址
     * </pre>
     *
     * <code>int64 remoteAddress = 2;</code>
     * @param value The remoteAddress to set.
     * @return This builder for chaining.
     */
    public Builder setRemoteAddress(long value) {
      
      remoteAddress_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *请求的远程IP地址
     * </pre>
     *
     * <code>int64 remoteAddress = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemoteAddress() {
      
      remoteAddress_ = 0L;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.github.mxsm.protocol.protobuf.MessageHeader)
  }

  // @@protoc_insertion_point(class_scope:com.github.mxsm.protocol.protobuf.MessageHeader)
  private static final MessageHeader DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new MessageHeader();
  }

  public static MessageHeader getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MessageHeader>
      PARSER = new com.google.protobuf.AbstractParser<MessageHeader>() {
    @Override
    public MessageHeader parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MessageHeader(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MessageHeader> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<MessageHeader> getParserForType() {
    return PARSER;
  }

  @Override
  public MessageHeader getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

