// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RequestHeaders.proto

package com.github.mxsm.protocol.protobuf;

public interface RequestHeadersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.protocol.protobuf.RequestHeaders)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *协议
   * </pre>
   *
   * <code>string protocol = 1;</code>
   * @return The protocol.
   */
  java.lang.String getProtocol();
  /**
   * <pre>
   *协议
   * </pre>
   *
   * <code>string protocol = 1;</code>
   * @return The bytes for protocol.
   */
  com.google.protobuf.ByteString
      getProtocolBytes();

  /**
   * <pre>
   *协议版本号
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   *协议版本号
   * </pre>
   *
   * <code>string version = 2;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <pre>
   *源IP
   * </pre>
   *
   * <code>int64 sourceAddress = 3;</code>
   * @return The sourceAddress.
   */
  long getSourceAddress();

  /**
   * <pre>
   *请求的远程IP地址
   * </pre>
   *
   * <code>int64 remoteAddress = 4;</code>
   * @return The remoteAddress.
   */
  long getRemoteAddress();

  /**
   * <pre>
   *内容类型
   * </pre>
   *
   * <code>string contentType = 6;</code>
   * @return The contentType.
   */
  java.lang.String getContentType();
  /**
   * <pre>
   *内容类型
   * </pre>
   *
   * <code>string contentType = 6;</code>
   * @return The bytes for contentType.
   */
  com.google.protobuf.ByteString
      getContentTypeBytes();

  /**
   * <pre>
   *发送消息的终端
   * </pre>
   *
   * <code>.com.github.mxsm.protocol.protobuf.TerminalType terminalType = 7;</code>
   * @return The enum numeric value on the wire for terminalType.
   */
  int getTerminalTypeValue();
  /**
   * <pre>
   *发送消息的终端
   * </pre>
   *
   * <code>.com.github.mxsm.protocol.protobuf.TerminalType terminalType = 7;</code>
   * @return The terminalType.
   */
  com.github.mxsm.protocol.protobuf.constant.TerminalType getTerminalType();

  /**
   * <pre>
   *发送消息的终端设备号
   * </pre>
   *
   * <code>string deviceToken = 8;</code>
   * @return The deviceToken.
   */
  java.lang.String getDeviceToken();
  /**
   * <pre>
   *发送消息的终端设备号
   * </pre>
   *
   * <code>string deviceToken = 8;</code>
   * @return The bytes for deviceToken.
   */
  com.google.protobuf.ByteString
      getDeviceTokenBytes();

  /**
   * <pre>
   *消息发送者
   * </pre>
   *
   * <code>string sender = 9;</code>
   * @return The sender.
   */
  java.lang.String getSender();
  /**
   * <pre>
   *消息发送者
   * </pre>
   *
   * <code>string sender = 9;</code>
   * @return The bytes for sender.
   */
  com.google.protobuf.ByteString
      getSenderBytes();

  /**
   * <pre>
   *消息接收者
   * </pre>
   *
   * <code>string receiver = 10;</code>
   * @return The receiver.
   */
  java.lang.String getReceiver();
  /**
   * <pre>
   *消息接收者
   * </pre>
   *
   * <code>string receiver = 10;</code>
   * @return The bytes for receiver.
   */
  com.google.protobuf.ByteString
      getReceiverBytes();
}
