// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MagpieBridge.proto

package com.github.mxsm.protocol.protobuf.magpiebridge;

public interface MagpieBridgeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.github.mxsm.protocol.protobuf.magpiebridge.MagpieBridge)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *名称
   * </pre>
   *
   * <code>string magpieBridgeName = 1;</code>
   * @return The magpieBridgeName.
   */
  java.lang.String getMagpieBridgeName();
  /**
   * <pre>
   *名称
   * </pre>
   *
   * <code>string magpieBridgeName = 1;</code>
   * @return The bytes for magpieBridgeName.
   */
  com.google.protobuf.ByteString
      getMagpieBridgeNameBytes();

  /**
   * <code>string magpieBridgeAddress = 2;</code>
   * @return The magpieBridgeAddress.
   */
  java.lang.String getMagpieBridgeAddress();
  /**
   * <code>string magpieBridgeAddress = 2;</code>
   * @return The bytes for magpieBridgeAddress.
   */
  com.google.protobuf.ByteString
      getMagpieBridgeAddressBytes();

  /**
   * <code>uint32 magpieBridgeId = 3;</code>
   * @return The magpieBridgeId.
   */
  int getMagpieBridgeId();
}
